<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/17/13
 */
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin',array('controller'=>'login','action' => 'auth')));
$form->prepare();
?>
<div class="container">
    <div class="login-form">
        <h2><?php echo $this->__('Login')?></h2>
        <?php echo $this->partial('partial/messages.phtml')?>
        <?php echo $this->form()->openTag($form);?>
        <div class="container">
            <div class="row row-form">
                <span class="control-label"><?php echo $this->__('Email')?></span>
                <?php echo $this->formRow($form->get('email'));?>
            </div>
            <div class="row row-form">
                <span class="control-label"><?php echo $this->__('Password')?></span>
                <?php echo $this->formRow($form->get('password'));?>
                <?php echo $this->formRow($form->get('csrf'));?>
            </div>
            <div class="row row-last">
                <button type="submit" class="btn btn-primary btn-lg">
                    <span><?php echo $this->__('Submit')?></span>
                </button>
            </div>
        </div>
        <?php echo $this->form()->closeTag();?>
    </div>
</div>