<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/17/13
 */
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin',array('controller'=>'login','action' => 'auth')));
$form->prepare();
?>
<div class="container">
    <div class="login-form">
        <h2><?php echo $this->translate('Login')?></h2>
        <?php echo $this->partial('partial/messages.phtml')?>
        <?php echo $this->form()->openTag($form);?>
            <div class="input-group">
                  <span class="input-group-btn">
                    <span class="btn btn-default" type="button"><?php echo $this->translate('Email')?> </span>
                  </span>
                <?php echo $this->formRow($form->get('email'));?>
            </div>
            <div class="input-group">
                  <span class="input-group-btn">
                    <span class="btn btn-default" type="button"><?php echo $this->translate('Password')?> </span>
                  </span>
                <?php echo $this->formRow($form->get('password'));?>
                <?php echo $this->formRow($form->get('csrf'));?>
            </div>
            <div class="input-group-action">
                <button type="submit" class="btn btn-primary btn-lg">
                    <span><?php echo $this->translate('Submit')?></span>
                </button>
            </div>
        <?php echo $this->form()->closeTag();?>
    </div>
</div>