<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<?php $form = $this->form;?>
<?php $form->setAttribute('action', $this->currentUrl());?>
<?php $form->prepare();?>
<div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-md-10">
        <div class="page-header">
            <div class="pull-left">
                <h3><?php echo $this->translate('New Recycler')?></h3>
            </div>
            <div class="pull-right">
                <a class="btn btn-sm btn-default add-item" href="/user"><i class="glyphicon glyphicon-arrow-left"></i><?php echo $this->translate('Back')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formReset('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-repeat"></i><?php echo $this->translate('Reset')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formSave('<?php echo $form->getAttribute('name');?>')"><i class="glyphicon glyphicon-saved"></i><?php echo $this->translate('Save')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formSaveAndContinue('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-save"></i><?php echo $this->translate('Save and Continue Edit')?></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <?php echo $this->partial('partial/form-messages.phtml',array('msg' => $this->msg))?>
    </div>
</div>
<?php echo $this->form()->openTag($form);?>
<?php echo $this->formRow($form->get('id'));?>
<?php echo $this->formRow($form->get('csrf'));?>
<?php echo $this->formRow($form->get('continue'));?>
<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked nav-tabs" data-tabs="tabs">
            <li class="active"><a data-toggle="tab" href="#recycler-info"><?php echo $this->translate('Recycler Information')?></a></li>
            <li><a data-toggle="tab" href="#device-model"><?php echo $this->translate('Device Models')?></a></li>
        </ul>
    </div>
    <div class="col-md-10">
        <div class="tab-content">
            <div class="tab-pane active" id="recycler-info">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><?php echo $this->translate('Individual Information')?></span>
                    </div>
                    <div class="panel-body">
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->translate('Recycler Name')?>* : </span>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('name'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->translate('Country')?>* : </span>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('country_id'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->translate('Email')?>* : </span>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('email'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->translate('Telephone')?> : </span>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('telephone'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->translate('Website')?> : </span>
                                </div>
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('website'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->translate('Address')?> : </span>
                                </div>
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('address'));?>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="device-model">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><?php echo $this->translate('Device Model List')?></span>
                    </div>
                    <div class="panel-body">
                        <div class="pull-right">
                            <a class="btn">
                                <?php echo $this->translate('Import from')?>
                            </a>
                            <div class="btn-group">
                                <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                    <?php echo $this->translate('Data Format')?> <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a><?php echo $this->translate('CSV')?></a></li>
                                    <li><a><?php echo $this->translate('Excel')?></a></li>
                                </ul>
                            </div>
                            <a class="btn btn-success btn-sm">
                                <i class="glyphicon glyphicon-upload"></i>
                                <?php echo $this->translate('Upload')?>
                            </a>
                        </div>
                        <div class="row clearfix">&nbsp;</div>
                        <table class="display table table-striped table-condensed table-bordered" id="example" cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th><?php echo $this->translate('ID')?></th>
                                <th><?php echo $this->translate('Device Model')?></th>
                                <th><?php echo $this->translate('Base Price')?></th>
                                <th><?php echo $this->translate('Exchange Price')?></th>
                                <th><?php echo $this->translate('TMD Model')?></th>
                                <th><?php echo $this->translate('TMD Price')?></th>
                                <th class="col-save"><?php echo $this->translate('Action')?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td>Device 1</td>
                                <td>100</td>
                                <td>200</td>
                                <td></td>
                                <td></td>
                                <td class="col-save">
                                    <a class="btn btn-sm btn-default">
                                        <i class="glyphicon glyphicon-save"></i>
                                        Save
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Device 2</td>
                                <td>100</td>
                                <td>200</td>
                                <td></td>
                                <td></td>
                                <td class="col-save">
                                    <a class="btn btn-sm btn-default">
                                        <i class="glyphicon glyphicon-save"></i>
                                        Save
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Device 3</td>
                                <td>100</td>
                                <td>200</td>
                                <td></td>
                                <td></td>
                                <td class="col-save">
                                    <a class="btn btn-sm btn-default">
                                        <i class="glyphicon glyphicon-save"></i>
                                        Save
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>Device 4</td>
                                <td>100</td>
                                <td>200</td>
                                <td></td>
                                <td></td>
                                <td class="col-save">
                                    <a class="btn btn-sm btn-default">
                                        <i class="glyphicon glyphicon-save"></i>
                                        Save
                                    </a>
                                </td>
                            </tr>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>
                                    <div class="input-group input-group-sm">
                                        <input type="text" class="form-control search_init" />
                                    </div>
                                </th>
                                <th>
                                    <div class="input-group input-group-sm">
                                        <input type="text" class="form-control search_init" />
                                    </div>
                                </th>
                                <th>
                                    <div class="input-group input-group-sm"><input type="text" class="form-control search_init" /></div>
                                </th>
                                <th>
                                    <div class="input-group input-group-sm">
                                        <input type="text" class="form-control search_init" />
                                    </div>
                                </th>
                                <th>
                                    <div class="input-group input-group-sm">
                                        <input type="text" class="form-control search_init" />
                                    </div>
                                </th>
                                <th>
                                    <div class="input-group input-group-sm">
                                        <input type="text" class="form-control search_init" />
                                    </div>
                                </th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag();?>