<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/14/13
 */
?>
<div class="page-header">
    <div class="pull-left">
        <h3>Exchange Rate</h3>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <span>Set time:</span>
                <div class="clearfix">&nbsp;</div>
                <div>
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">Start time</span>
                        <input class="form-control datepicker" name="start-time" id="start-time">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>
                </div>
                <div class="clearfix">&nbsp;</div>
                <div>
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon">End time</span>
                        <input class="form-control datepicker" name="end-time" id="end-time">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>
                </div>
                <br/>
                <span>Select currency:</span>
                <div class="clearfix">&nbsp;</div>
                <div class="form-group">
                    <select id="select-currency" class="form-control" style="width: 50%;">
                        <?php $currencies = $this->exchange()->getAvailableCurrencies();?>
                        <?php if(!empty($currencies)): ?>
                        <?php foreach($currencies as $key=>$currency):?>
                            <option value="<?php echo $key?>"><?php echo $currency?></option>
                        <?php endforeach;?>
                        <?php endif;?>
                    </select>
                </div>
                <div class="clearfix">&nbsp;</div>
                <br/>
                <div class="form-group">
                    <ul class="nav-tabs nav-pills" data-tabs="tabs" id="model-view-tabs">
                        <li class="active">
                            <a class="btn btn-sm" data-toggle="tab" href="#chart-view">
                                <i class="glyphicon glyphicon-stats"></i>
                                Chart
                            </a>
                        </li>
                        <li>
                            <a class="btn btn-sm" data-toggle="tab" href="#table-view">
                                <i class="glyphicon glyphicon-th"></i>
                                Table
                            </a>
                        </li>
                    </ul>
                    <button class="btn btn-success btn-sm btn-load-exchange" onclick="loadExchangeData()"><span>Submit</span></button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane active" id="chart-view">
                        <img src="/images/loading.gif" width="48px" style="width: 48px;">
                    </div>
                    <div class="tab-pane " id="table-view">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>