<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/14/13
 */
?>
<?php $form = $this->form;?>
<?php $form->setAttribute('action', $this->currentUrl());?>
<?php $form->prepare();?>
<div class="page-header">
    <div class="pull-left">
        <h3><?php echo $this->__('New Exchange Rate')?></h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-sm btn-default add-item" href="/exchange"><i class="glyphicon glyphicon-arrow-left"></i><?php echo $this->__('Back')?></a>
        <a class="btn btn-sm btn-default add-item" onclick="formReset('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-repeat"></i><?php echo $this->__('Reset')?></a>
        <a class="btn btn-sm btn-default add-item" onclick="formSave('<?php echo $form->getAttribute('name');?>')"><i class="glyphicon glyphicon-saved"></i><?php echo $this->__('Save')?></a>
        <a class="btn btn-sm btn-default add-item" onclick="formSaveAndContinue('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-save"></i><?php echo $this->__('Save and Continue Edit')?></a>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
<?php echo $this->form()->openTag($form);?>
<div class="panel">
    <div class="panel-body">
        <div class="row form-row">
            <?php echo $this->partial('partial/form-messages.phtml',array('msg' => $this->msg))?>
        </div>
        <div class="row form-row">
            <div class="col-md-3 required"><span class="pull-right"><?php echo $this->__('Currency')?><em>*</em></span></div>
            <div class="col-md-3">
                <?php echo $this->formRow($form->get('currency'));?>
                <?php echo $this->formRow($form->get('continue'));?>
            </div>
        </div>
        <div class="row form-row">
            <div class="col-md-3 required"><span class="pull-right"><?php echo $this->__('Date')?></span></div>
            <div class="col-md-9">
                <div class="input-group" style="width: 150px;float: left;">
                    <?php echo $this->formRow($form->get('time'));?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                </div>
            </div>
        </div>
        <div class="row form-row">
            <div class="col-md-3 required"><span class="pull-right"><?php echo $this->__('Exchange Rate')?><em>*</em></span></div>
            <div class="col-md-3">
                <?php echo $this->formRow($form->get('exchange_rate'));?>
                <?php echo $this->formRow($form->get('csrf'));?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag();?>