<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<?php $form = $this->form;?>
<?php $form->setAttribute('action', $this->currentUrl());?>
<?php $form->prepare();?>
<div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-md-10">
        <div class="page-header">
            <div class="pull-left">
                <h3><?php echo $this->__('New Recycler')?></h3>
            </div>
            <div class="pull-right">
                <a class="btn btn-sm btn-default add-item" href="/recycler"><i class="glyphicon glyphicon-arrow-left"></i><?php echo $this->__('Back')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formReset('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-repeat"></i><?php echo $this->__('Reset')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formSave('<?php echo $form->getAttribute('name');?>')"><i class="glyphicon glyphicon-saved"></i><?php echo $this->__('Save')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formSaveAndContinue('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-save"></i><?php echo $this->__('Save and Continue Edit')?></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <?php echo $this->partial('partial/form-messages.phtml',array('msg' => $this->msg))?>
    </div>
</div>
<?php echo $this->form()->openTag($form);?>
<?php echo $this->formRow($form->get('recycler_id'));?>
<?php echo $this->formRow($form->get('csrf'));?>
<?php echo $this->formRow($form->get('continue'));?>
<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked nav-tabs" data-tabs="tabs">
            <li class="active"><a data-toggle="tab" href="#recycler-info"><?php echo $this->__('Recycler Information')?></a></li>
            <li><a data-toggle="tab" href="#product-model"><?php echo $this->__('Product Models')?></a></li>
        </ul>
    </div>
    <div class="col-md-10">
        <div class="tab-content">
            <div class="tab-pane active" id="recycler-info">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><?php echo $this->__('Individual Information')?></span>
                    </div>
                    <div class="panel-body">
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->__('Recycler Name')?>* : </span>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('name'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->__('Country')?>* : </span>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('country_id'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->__('Email')?>* : </span>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('email'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->__('Telephone')?> : </span>
                                </div>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($form->get('telephone'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->__('Website')?> : </span>
                                </div>
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('website'));?>
                                </div>
                            </div>
                            <div class="row form-row">
                                <div class="col-md-4">
                                    <span class="pull-right"><?php echo $this->__('Address')?> : </span>
                                </div>
                                <div class="col-md-6">
                                    <?php echo $this->formRow($form->get('address'));?>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="product-model">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><?php echo $this->__('Product Model List')?></span>
                    </div>
                    <div class="panel-body">
                        <h3><?php echo $this->__('You must save this recycler.')?></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag();?>

