<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<?php
$temp_ids = $this->recyclerImported()->getAllTempProductInRecycler($this->id);
?>
<?php $form = $this->form;?>
<?php $form->setAttribute('action', $this->currentUrl());?>
<?php $form->prepare();?>
<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-10">
        <div class="page-header">
            <div class="pull-left">
                <h3><?php echo $this->recycler?></h3>
            </div>
            <div class="pull-right">
                <a class="btn btn-sm btn-default add-item" href="/recycler"><i class="glyphicon glyphicon-arrow-left"></i><?php echo $this->translate('Back')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formSave('<?php echo $form->getAttribute('name');?>')"><i class="glyphicon glyphicon-saved"></i><?php echo $this->translate('Save')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formSaveAndContinue('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-save"></i><?php echo $this->translate('Save and Continue Edit')?></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <?php echo $this->partial('partial/form-messages.phtml',array('msg' => $this->msg))?>
    </div>
</div>
<?php echo $this->form()->openTag($form);?>
<?php echo $this->formRow($form->get('recycler_id'));?>
<?php echo $this->formRow($form->get('csrf'));?>
<?php echo $this->formRow($form->get('continue'));?>
<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked nav-tabs" data-tabs="tabs">
            <li class="active"><a data-toggle="tab" href="#recycler-view"><?php echo $this->translate('Recycler View')?></a></li>
            <li><a data-toggle="tab" href="#product-model"><?php echo $this->translate('Product Models')?></a></li>
        </ul>

    </div>
    <div class="col-md-10">
        <div id="show-msg"></div>
        <div class="row clearfix">&nbsp;</div>
        <div class="tab-content">
            <div class="tab-pane active" id="recycler-view">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><?php echo $this->translate('Individual Information')?></span>
                    </div>
                    <div class="panel-body">
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->translate('Recycler Name')?>* : </span>
                            </div>
                            <div class="col-md-4">
                                <?php echo $this->formRow($form->get('name'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->translate('Country')?>* : </span>
                            </div>
                            <div class="col-md-4">
                                <?php echo $this->formRow($form->get('country_id'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->translate('Email')?>* : </span>
                            </div>
                            <div class="col-md-4">
                                <?php echo $this->formRow($form->get('email'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->translate('Telephone')?> : </span>
                            </div>
                            <div class="col-md-4">
                                <?php echo $this->formRow($form->get('telephone'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->translate('Website')?> : </span>
                            </div>
                            <div class="col-md-6">
                                <?php echo $this->formRow($form->get('website'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->translate('Address')?> : </span>
                            </div>
                            <div class="col-md-6">
                                <?php echo $this->formRow($form->get('address'));?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="product-model">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><?php echo $this->translate('Product Model List')?></span>
                    </div>
                    <div class="panel-body">
                        <div class="pull-right">
                            <a class="btn">
                                <?php echo $this->translate('Import from')?>
                            </a>
                            <div class="btn-group">
                                <select class="form-control" id="import-format" name="import_format">
                                    <option><?php echo $this->translate('Select format')?></option>
                                    <option value="csv"><?php echo $this->translate('CSV')?></option>
                                    <option value="xls"><?php echo $this->translate('Excel 2003')?></option>
                                    <option value="xlsx"><?php echo $this->translate('Excel 2007')?></option>
                                </select>
                            </div>
                            <a class="btn btn-success btn-sm uploadform">
                                <i class="glyphicon glyphicon-upload"></i>
                                <?php echo $this->translate('Upload')?>
                            </a>
                        </div>
                        <div class="row clearfix">&nbsp;</div>
                        <table class="display table table-striped table-condensed table-bordered example" id="model-table" cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                                <th><?php echo $this->translate('Product Name')?></th>
                                <th><?php echo $this->translate('Base Price')?></th>
                                <th><?php echo $this->translate('Currency')?></th>
                                <th><?php echo $this->translate('TDM Product Name')?></th>
                                <th><?php echo $this->translate('TDM Price')?></th>
                                <th class="col-save"><?php echo $this->translate('Action')?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if(!empty($this->tmpProducts)):?>
                            <?php $i =1;?>
                            <?php foreach($this->tmpProducts as $row):?>
                                <tr>
                                    <td class="col-checkbox"><input name="ids[]" type="checkbox" class="check-item" <?php if(in_array($row->id,$temp_ids)){echo 'checked';}?> value="<?php echo $row->id?>"></td>
                                    <td><?php echo $row->name?></td>
                                    <td><?php echo $row->price?></td>
                                    <td><?php echo $row->currency?></td>
                                    <td><?php echo $row->model?></td>
                                    <td></td>
                                    <td class="col-save">
                                        <a class="btn btn-sm btn-default" onclick="saveImportRecord('/recycler/save-import/id/<?php echo $row->id?>')">
                                            <i class="glyphicon glyphicon-save"></i>
                                            <?php echo $this->translate('Save')?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag();?>
<div style="display: none">
    <div id="upload-form">
        <form id="import-form" method="post" action="/recycler/import" enctype="multipart/form-data">
            <?php echo $this->formRow($form->get('recycler_id'));?>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('Import Recycler Models')?></h3>
                </div>
                <div class="panel-body">
                    <div class="row form-row">
                        <div class="col-md-3">
                            <div class="control-label"><span><?php echo $this->translate('File')?> : </span></div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-control">
                                <input type="file" name="upload_file" id="import-file">
                            </div>
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9" id="upload-action">
                            <button type="submit" class="btn btn-success btn-sm" id="upload-button">
                                <i class="glyphicon glyphicon-upload"></i>
                                <span><?php echo $this->translate('Upload')?></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>