<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<?php
$temp_ids = $this->recyclerImported()->getAllTempProductInRecycler($this->id);
$upload = $this->upload;
$from = $this->from;
?>
<?php if($upload == 'success' || $from == 'delete' || !empty($this->ppp) || !empty($this->page)):?>
    <script type="text/javascript">
        $(function(){
            $('a[href=#product-model]').tab('show');
        });
    </script>
<?php endif;?>
<?php $form = $this->form;?>
<?php $form->setAttribute('action', $this->currentUrl());?>
<?php $form->prepare();?>
<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-10">
        <div class="page-header">
            <div class="pull-left">
                <h3><?php echo $this->recycler?></h3>
            </div>
            <div class="pull-right">
                <a class="btn btn-sm btn-default add-item" href="/recycler"><i class="glyphicon glyphicon-arrow-left"></i><?php echo $this->__('Back')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formSave('<?php echo $form->getAttribute('name');?>')"><i class="glyphicon glyphicon-saved"></i><?php echo $this->__('Save')?></a>
                <a class="btn btn-sm btn-default add-item" onclick="formSaveAndContinue('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-save"></i><?php echo $this->__('Save and Continue Edit')?></a>
            </div>
            <div class="clearfix"></div>
        </div>
        <?php echo $this->partial('partial/form-messages.phtml',array('msg' => $this->msg))?>
    </div>
</div>
<?php echo $this->form()->openTag($form);?>
<?php echo $this->formRow($form->get('recycler_id'));?>
<?php echo $this->formRow($form->get('csrf'));?>
<?php echo $this->formRow($form->get('continue'));?>
<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked nav-tabs" data-tabs="tabs">
            <li class="active"><a data-toggle="tab" href="#recycler-view"><?php echo $this->__('Recycler View')?></a></li>
            <li><a data-toggle="tab" href="#product-model"><?php echo $this->__('Product Models')?></a></li>
        </ul>

    </div>
    <div class="col-md-10">
        <div id="show-msg"></div>
        <div class="row clearfix">&nbsp;</div>
        <div class="tab-content">
            <div class="tab-pane active" id="recycler-view">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><?php echo $this->__('Individual Information')?></span>
                    </div>
                    <div class="panel-body">
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->__('Recycler Name')?>* : </span>
                            </div>
                            <div class="col-md-4">
                                <?php echo $this->formRow($form->get('name'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->__('Country')?>* : </span>
                            </div>
                            <div class="col-md-4">
                                <?php echo $this->formRow($form->get('country_id'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->__('Email')?>* : </span>
                            </div>
                            <div class="col-md-4">
                                <?php echo $this->formRow($form->get('email'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->__('Telephone')?> : </span>
                            </div>
                            <div class="col-md-4">
                                <?php echo $this->formRow($form->get('telephone'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->__('Website')?> : </span>
                            </div>
                            <div class="col-md-6">
                                <?php echo $this->formRow($form->get('website'));?>
                            </div>
                        </div>
                        <div class="row form-row">
                            <div class="col-md-4">
                                <span class="pull-right"><?php echo $this->__('Address')?> : </span>
                            </div>
                            <div class="col-md-6">
                                <?php echo $this->formRow($form->get('address'));?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="product-model">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><?php echo $this->__('Product Model List')?></span>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left" style="margin-bottom: 15px;">
                            <a class="btn btn-outline">
                                <?php echo $this->__('Export to')?>
                            </a>
                            <div class="btn-group">
                                <select class="form-control" id="export-format" name="export_format">
                                    <option value="none"><?php echo $this->__('Select format')?></option>
                                    <option value="csv"><?php echo $this->__('CSV')?></option>
                                    <option value="xls"><?php echo $this->__('Excel 2003')?></option>
                                    <option value="xlsx"><?php echo $this->__('Excel 2007')?></option>
                                </select>
                            </div>
                            <a class="btn btn-warning btn-sm" onclick="exportRecyclerProducts('<?php echo $this->id?>');">
                                <i class="glyphicon glyphicon-export"></i>
                                <?php echo $this->__('Export')?>
                            </a>
                        </div>
                        <div class="pull-right" style="margin-bottom: 15px;">
                            <a class="btn btn-danger btn-sm delete-selected" onclick="delete_recycler_products();">
                                <i class="glyphicon glyphicon-upload"></i>
                                <?php echo $this->__('Delete Selected')?>
                            </a>
                            <a class="btn">
                                <?php echo $this->__('Import from')?>
                            </a>
                            <div class="btn-group">
                                <select class="form-control" id="import-format" name="import_format">
                                    <option><?php echo $this->__('Select format')?></option>
                                    <option value="csv"><?php echo $this->__('CSV')?></option>
                                    <option value="xls"><?php echo $this->__('Excel 2003')?></option>
                                    <option value="xlsx"><?php echo $this->__('Excel 2007')?></option>
                                </select>
                            </div>
                            <a class="btn btn-success btn-sm uploadform">
                                <i class="glyphicon glyphicon-upload"></i>
                                <?php echo $this->__('Upload')?>
                            </a>
                            <?php if($this->upload == 'success'):?>
                            <a class="btn btn-sm btn-success" onclick="saveallimported('<?php echo $this->id?>')">
                                <i class="glyphicon glyphicon-save"></i>
                                <?php echo $this->__('Save all')?>
                            </a>
                            <?php endif;?>
                        </div>
                        <div class="row clearfix">&nbsp;</div>
                        <table class="display table table-striped table-condensed table-bordered withphp" id="model-table" cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                                <th><?php echo $this->__('ID')?></th>
                                <th><?php echo $this->__('Product Name')?></th>
                                <th><?php echo $this->__('Condition')?></th>
                                <th><?php echo $this->__('Date time')?></th>
                                <th><?php echo $this->__('Base Price')?></th>
                                <th><?php echo $this->__('Currency')?></th>
                                <th><?php echo $this->__('Price in HKD')?></th>
                                <th><?php echo $this->__('TDM Product Name')?></th>
                                <th><?php echo $this->__('SSA Price')?></th>
                                <th><?php echo $this->__('Action')?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if(count($this->products)):?>
                            <?php foreach($this->products as $product):?>
                                <tr>
                                    <td class="col-checkbox"><input value="<?php echo $product->product_id?>" type="checkbox" name="recycler_products[]" class="recycler-product check-item"></td>
                                    <td><?php echo $product->product_id?></td>
                                    <td><?php echo $product->name?></td>
                                    <td><?php echo $this->condition($product->condition_id,false)?></td>
                                    <td><?php echo (!empty($product->date)) ? date('d-m-Y',$product->date) : 'N/A'?></td>
                                    <td><?php echo $this->price()->formatCurrency($product->price,$product->currency)?></td>
                                    <td><?php echo $product->currency?></td>
                                    <?php $rExchange = $this->exchange()->getCurrentExchangeOfCurrency($product->currency,time());?>
                                    <td><?php echo $this->price()->formatCurrency((float)$product->price/ $rExchange,'HKD');?></td>
                                    <?php $tdmProduct = $this->recyclerImported()->getTdmProductWithSameModel($product->model,$product->condition_id);?>
                                    <?php if(!empty($tdmProduct)):?>
                                        <td><?php echo $tdmProduct->name?></td>
                                        <?php $tdmPrice = $this->product()->getSSAPrice($tdmProduct->model,$tdmProduct->condition_id);?>
                                        <td><?php echo $this->price()->formatCurrency($tdmPrice,'HKD');?></td>
                                    <?php else:?>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                    <?php endif;?>
                                    <td>
                                        <a class="btn btn-xs btn-primary btn-edit" href="/recycler/product/id/<?php echo $product->product_id?>"><?php echo $this->__('Edit')?></a>
                                        <a class="btn btn-xs btn-danger btn-edit" onclick="confirmDelete('<?php echo $this->getUrl('/recycler/delete-product/recycler/'.$this->id.'/id/'.$product->product_id)?>');" ><?php echo $this->__('Delete')?></a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                            <?php endif;?>
                            <?php if(count($this->tmpProducts)):?>
                            <?php $i =1;?>
                            <?php foreach($this->tmpProducts as $row):?>
                                <tr>
                                    <td class="col-checkbox"><input name="ids[]" type="checkbox" class="check-item" <?php if(!empty($temp_ids) && in_array($row->id,$temp_ids)){echo 'checked';}?> value="<?php echo $row->id?>"></td>
                                    <td><?php echo $i++?></td>
                                    <td><?php echo $row->name?></td>
                                    <td><?php echo $this->condition($row->condition_id,false)?></td>
                                    <td><?php echo $row->date?></td>
                                    <td><?php echo $this->price()->formatCurrency($row->price,$row->currency)?></td>
                                    <td><?php echo $row->currency?></td>
                                    <?php $rExchange2 = $this->exchange()->getCurrentExchangeOfCurrency($row->currency,time());?>
                                    <td><?php echo $this->price()->formatCurrency((float)$row->price/$rExchange2,$row->currency);?></td>
                                    <?php $tdmProduct = $this->recyclerImported()->getTdmProductWithSameModel($row->model,$row->condition_id);?>
                                    <?php if(!empty($tdmProduct)):?>
                                        <td><?php echo $tdmProduct->name?></td>
                                        <?php $tdmPrice = $this->product()->getSSAPrice($tdmProduct->model,$tdmProduct->condition_id);?>
                                        <td><?php echo $this->price()->formatCurrency($tdmPrice,'HKD');?></td>
                                    <?php else:?>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                    <?php endif;?>
                                    <td>
                                        <a id="btn-<?php echo $row->id?>" class="btn btn-xs btn-primary btn-save-import" onclick="saveImportRecord('/recycler/save-import/id/<?php echo $row->id?>',this.id)">
                                            <?php echo $this->__('Save')?>
                                        </a>
                                        <a class="btn btn-xs btn-primary" href="/recycler/temp/id/<?php echo $row->id?>"><?php echo $this->__('Edit')?></a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                        <?php if(count($this->tmpProducts)):?>
                            <?php echo $this->paginationControl($this->tmpProducts,
                                'Sliding',
                                'paginator_style_2', array('route' => 'recycler-detail-upload','id' => $this->id)); ?>
                        <?php elseif(count($this->products)):?>
                            <?php echo $this->paginationControl($this->products,
                                'Sliding',
                                'paginator_style_2', array('route' => 'recycler-detail','id' => $this->id)); ?>
                        <?php endif?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag();?>
<div style="display: none">
    <div id="upload-form">
        <form id="import-form" method="post" action="/recycler/import" enctype="multipart/form-data">
            <?php echo $this->formRow($form->get('recycler_id'));?>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->__('Import Recycler Models')?></h3>
                </div>
                <div class="panel-body">
                    <div class="row form-row">
                        <div class="col-md-3">
                            <div class="control-label"><span><?php echo $this->__('File')?> : </span></div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-control">
                                <input type="file" name="upload_file" id="import-file">
                            </div>
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9" id="upload-action">
                            <button type="submit" class="btn btn-success btn-sm" id="upload-button">
                                <i class="glyphicon glyphicon-upload"></i>
                                <span><?php echo $this->__('Upload')?></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>