<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-10">
        <div class="page-header">
            <div class="pull-left">
                <h3>Recycler name XXX</h3>
            </div>
            <div class="pull-right">
                <a class="btn btn-default btn-sm back-top" href="/recycler">
                    <i class="glyphicon glyphicon-backward"></i>
                    Back
                </a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked nav-tabs" data-tabs="tabs">
            <li class="active"><a data-toggle="tab" href="#recycler-view">Recycler View</a></li>
            <li><a data-toggle="tab" href="#device-model">Device Model</a></li>
        </ul>

    </div>
    <div class="col-md-10">
        <div class="tab-content">
            <div class="tab-pane active" id="recycler-view">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span>Individual Information</span>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="device-model">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span>Device Model List</span>
                    </div>
                    <div class="panel-body">
                        <div class="pull-right">
                            <a class="btn">
                                Export to
                            </a>
                            <div class="btn-group">
                                <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                    Small button <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a>CSV</a></li>
                                    <li><a>Excel</a></li>
                                </ul>
                            </div>
                            <a class="btn btn-warning btn-sm">
                                <i class="glyphicon glyphicon-export"></i>
                                Export
                            </a>
                            <a class="btn btn-default btn-sm">
                                <i class="glyphicon glyphicon-refresh"></i>
                                Reset filter
                            </a>
                        </div>
                        <div class="row clearfix">&nbsp;</div>
                        <table class="display table table-striped table-condensed table-bordered" id="example" cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                                <th><?php echo $this->translate('ID')?></th>
                                <th><?php echo $this->translate('Device Model')?></th>
                                <th><?php echo $this->translate('Base Price')?></th>
                                <th><?php echo $this->translate('Exchange Price')?></th>
                                <th><?php echo $this->translate('Data')?></th>
                                <th><?php echo $this->translate('TMD Model')?></th>
                                <th><?php echo $this->translate('TMD Price')?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                <td>2</td>
                                <td>Admin</td>
                                <td>Vietnam</td>
                                <td>admin2@mail.com</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                <td>2</td>
                                <td>Admin</td>
                                <td>Vietnam</td>
                                <td>admin2@mail.com</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                <td>2</td>
                                <td>Admin</td>
                                <td>Vietnam</td>
                                <td>admin2@mail.com</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                <td>2</td>
                                <td>Admin</td>
                                <td>Vietnam</td>
                                <td>admin2@mail.com</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th></th>
                                <th><input type="text" name="search_id" value="<?php echo $this->translate('Search id')?>" class="search_init" /></th>
                                <th><input type="text" name="search_device" value="<?php echo $this->translate('Search device')?>" class="search_init" /></th>
                                <th><input type="text" name="search_price" value="<?php echo $this->translate('Search price')?>" class="search_init" /></th>
                                <th><input type="text" name="search_ex_price" value="<?php echo $this->translate('Search exchange price')?>" class="search_init" /></th>
                                <th><input type="text" name="search_data" value="<?php echo $this->translate('Search data')?>" class="search_init" /></th>
                                <th><input type="text" name="search_tmd_model" value="<?php echo $this->translate('Search model')?>" class="search_init" /></th>
                                <th><input type="text" name="search_tmd_price" value="<?php echo $this->translate('Search price')?>" class="search_init" /></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
