<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/28/13
 */
?>
<?php $form = $this->form;?>
<?php $form->setAttribute('action', $this->currentUrl());?>
<?php $form->prepare();?>
    <div class="page-header">
        <div class="pull-left">
            <h3><?php echo $this->model?></h3>
        </div>
        <div class="pull-right">
            <a class="btn btn-sm btn-default add-item" href="/product"><i class="glyphicon glyphicon-arrow-left"></i><?php echo $this->translate('Back')?></a>
            <a class="btn btn-sm btn-default add-item" onclick="formReset('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-repeat"></i><?php echo $this->translate('Reset')?></a>
            <a class="btn btn-sm btn-default add-item" onclick="formSave('<?php echo $form->getAttribute('name');?>')"><i class="glyphicon glyphicon-saved"></i><?php echo $this->translate('Save')?></a>
            <a class="btn btn-sm btn-default add-item" onclick="formSaveAndContinue('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-save"></i><?php echo $this->translate('Save and Continue Edit')?></a>
        </div>
        <div class="clearfix">&nbsp;</div>
    </div>
<?php echo $this->form()->openTag($form);?>
<?php echo $this->formRow($form->get('product_id'));?>
<?php echo $this->formRow($form->get('csrf'));?>
<?php echo $this->formRow($form->get('continue'));?>
    <div class="panel">
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <?php echo $this->partial('partial/form-messages.phtml',array('msg' => $this->msg))?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3"><span class="pull-right"><?php echo $this->translate('Product Name')?>*</span></div>
                <div class="col-md-6">
                    <?php echo $this->formRow($form->get('name'));?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3"><span class="pull-right"><?php echo $this->translate('Brand')?>*</span></div>
                <div class="col-md-6">
                    <?php echo $this->formRow($form->get('brand_id'));?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <span class="pull-right"><?php echo $this->translate('Model')?>*</span>
                </div>
                <div class="col-md-6">
                    <?php echo $this->formRow($form->get('model'));?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <span class="pull-right"><?php echo $this->translate('Product Type')?>*</span>
                </div>
                <div class="col-md-3">
                    <?php echo $this->formRow($form->get('type_id'));?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3"><span class="pull-right"><?php echo $this->translate('Condition')?>*</span></div>
                <div class="col-md-3">
                    <?php echo $this->formRow($form->get('condition_id'));?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3"><span class="pull-right"><?php echo $this->translate('')?>Price*</span></div>
                <div class="col-md-3">
                    <?php echo $this->formRow($form->get('price'));?>
                </div>

            </div>
            <div class="form-group">
                <div class="col-md-3"><span class="pull-right"><?php echo $this->translate('')?>Currency*</span></div>
                <div class="col-md-3">
                    <?php echo $this->formRow($form->get('currency'));?>
                </div>
            </div>
        </div>
    </div>
<?php echo $this->form()->closeTag();?>