<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<?php $product = $this->entry;?>
<?php
$product_price = $product->price;
$productExchangePrice = $this->price()->getExchange($product_price,$product->currency);
echo $productExchangePrice;
?>
<div class="page-header">
    <div class="pull-left">
        <h3><?php echo $this->name?></h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-default btn-sm back-top" href="/product/">
            <i class="glyphicon glyphicon-arrow-left"></i>
            <?php echo $this->translate('Back')?>
        </a>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked nav-tabs" data-tabs="tabs">
            <li class="active"><a data-toggle="tab" href="#price-comparision"><?php echo $this->translate('Price Comparison')?></a></li>
            <li><a data-toggle="tab" href="#historical-prices"><?php echo $this->translate('Historical Prices')?></a></li>
        </ul>
    </div>
    <div class="col-md-10">
        <div class="tab-content">
            <div class="tab-pane active" id="price-comparision">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div>
                            <div class="pull-left">
                                <a class="btn btn-outline"><?php echo $this->translate('Notice')?></a>
                                <div class="btn btn-default">
                                    <?php echo $this->translate('Price higher than 50%(xx)')?>
                                </div>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-outline">
                                    <?php echo $this->translate('Export to')?>
                                </a>
                                <div class="btn-group">
                                    <select class="form-control" id="export-format" name="export_format">
                                        <option value="none"><?php echo $this->translate('Select format')?></option>
                                        <option value="csv"><?php echo $this->translate('CSV')?></option>
                                        <option value="xls"><?php echo $this->translate('Excel 2003')?></option>
                                        <option value="xlsx"><?php echo $this->translate('Excel 2007')?></option>
                                    </select>
                                </div>
                                <a class="btn btn-warning btn-sm">
                                    <i class="glyphicon glyphicon-export"></i>
                                    <?php echo $this->translate('Export')?>
                                </a>
                            </div>
                        </div>
                        <div class="row clearfix">&nbsp;</div>
                        <table class="display table table-striped table-condensed table-bordered example" id="example" cellpadding="0" cellspacing="0">
                        <thead>
                        <tr>
                            <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                            <th><?php echo $this->translate('Recycler Id')?></th>
                            <th><?php echo $this->translate('Recycler Name')?></th>
                            <th><?php echo $this->translate('Country')?></th>
                            <th><?php echo $this->translate('Product Name')?></th>
                            <th><?php echo $this->translate('Price')?></th>
                            <th><?php echo $this->translate('Exchange Price')?></th>
                            <th><?php echo $this->translate('%')?></th>
                            <th><?php echo $this->translate('Tdm Exchange Price')?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if(!empty($this->products)):?>
                        <?php foreach($this->products as $_product):?>
                            <tr>
                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="<?php echo $_product->product_id?>"></td>
                                <td><?php echo $_product->recycler_id?></td>
                                <td><?php echo $this->recycler()->getName($_product->recycler_id)?></td>
                                <td><?php echo $this->recycler()->getCountryName($_product->recycler_id)?></td>
                                <td><?php echo $_product->name;?></td>
                                <td><?php echo $this->price()->format($_product->price);?></td>
                                <td><?php echo $this->price()->format($this->price()->getExchange($_product->price,$_product->currency))?></td>
                                <td><?php echo $this->price()->getPercent($this->price()->getExchange($_product->price,$_product->currency),$productExchangePrice)?></td>
                                <td><?php echo $this->price()->format($productExchangePrice)?></td>
                            </tr>
                        <?php endforeach;?>
                        <?php endif;?>
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="historical-prices">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row form-row">
                                    <div class="col-md-2">
                                        <a class="btn btn-outline"><?php echo $this->translate('')?>Set time :</a>
                                    </div>
                                    <div class="col-md-10">
                                        <div class="row">
                                            <div class="pull-left">
                                                <div class="input-group input-group-sm">
                                                    <span class="input-group-addon"><?php echo $this->translate('')?>Start time</span>
                                                    <input class="form-control datepicker" name="start-time" id="start-time">
                                                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                                </div>
                                            </div>
                                            <div class="pull-left">
                                                <div class="input-group input-group-sm">
                                                    <span class="input-group-addon"><?php echo $this->translate('')?>End time</span>
                                                    <input class="form-control datepicker" name="end-time" id="end-time">
                                                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row form-row">
                                    <div class="col-md-2">
                                        <a class="btn btn-outline">Search by :</a>
                                    </div>
                                    <div class="col-md-10">
                                        <div class="row">
                                            <input type="radio" name="search">
                                            <span><?php echo $this->translate('')?>Recycler</span>
                                            <select>
                                                <option><?php echo $this->translate('')?>Recycler Name</option>
                                                <option><?php echo $this->translate('')?>Recycler Brand</option>
                                                <option><?php echo $this->translate('')?>Recycler Type</option>
                                            </select>
                                        </div>
                                        <div class="row form-row">
                                            <input type="radio" name="search">
                                            <span><?php echo $this->translate('')?>Highest price</span>
                                        </div>

                                    </div>
                                </div>
                                <div class="clearfix">&nbsp;</div>
                                <div class="pull-left">
                                    <a onclick="submitHistoricalModelPrice();" class="btn btn-sm btn-success">
                                        <i class="glyphicon glyphicon-ok"></i>
                                        <?php echo $this->translate('Submit');?>
                                    </a>
                                </div>
                                <div class="pull-right">
                                    <ul class="nav-tabs nav-pills" data-tabs="tabs" id="model-view-tabs">
                                        <li>
                                            <a class="btn btn-sm" data-toggle="tab" href="#chart-view">
                                                <i class="glyphicon glyphicon-stats"></i>
                                                <?php echo $this->translate('Chart')?>
                                            </a>
                                        </li>
                                        <li class="active">
                                            <a class="btn btn-sm" data-toggle="tab" href="#table-view">
                                                <i class="glyphicon glyphicon-th"></i>
                                                <?php echo $this->translate('Table')?>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                        <div class="pull-right">
                            <a class="btn">
                                <?php echo $this->translate('')?>Export to
                            </a>
                            <div class="btn-group">
                                <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                                    <?php echo $this->translate('')?>Data format <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a><?php echo $this->translate('')?>CSV</a></li>
                                    <li><a><?php echo $this->translate('')?>Excel</a></li>
                                </ul>
                            </div>
                            <a class="btn btn-warning btn-sm">
                                <i class="glyphicon glyphicon-export"></i>
                                <?php echo $this->translate('')?>Export
                            </a>
                        </div>
                        <div class="clearfix">&nbsp;</div>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="tab-content">
                                    <div class="tab-pane active" id="table-view">
                                        <table class="display table table-striped table-condensed table-bordered example" id="example2" cellpadding="0" cellspacing="0">
                                            <thead>
                                            <tr>
                                                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                                                <th><?php echo $this->translate('Date')?></th>
                                                <th><?php echo $this->translate('Price')?></th>
                                                <th><?php echo $this->translate('Price in HKD')?></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="tab-pane" id="chart-view">
                                        <div id="chart-demo" class="chart-demo">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>