<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<?php $product = $this->entry;?>
<?php
$product_price = $this->product()->getSSAPrice($product->model,$product->condition_id);
?>
<div class="page-header">
    <div class="pull-left">
        <h3><?php echo $this->name?></h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-default btn-sm back-top" id="back-button" href="<?php echo $this->getUrl('product')?>">
            <i class="glyphicon glyphicon-arrow-left"></i>
            <?php echo $this->__('Back')?>
        </a>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
<div class="row" id="product-detail">
<input type="hidden" name="product" id="productid" value="<?php echo $this->id?>">
<input type="hidden" value="<?php echo $this->country?>" name="tdm_country" id="tdm-country">
<input type="hidden" value="<?php echo $this->recycler_country?>" name="recycler_country" id="recycler-country">
<input type="hidden" value="<?php echo $this->higher?>" name="filter_higher" id="filter-higher">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked nav-tabs" data-tabs="tabs">
            <li class="active"><a data-toggle="tab" href="#price-comparision"><?php echo $this->__('Price Comparison')?></a></li>
            <li><a data-toggle="tab" href="#historical-prices"><?php echo $this->__('Historical Prices')?></a></li>
        </ul>
    </div>
    <div class="col-md-10">
        <div class="tab-content">
            <div class="tab-pane active" id="price-comparision">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php if(is_numeric($this->filter) ){?>
                            <script type="text/javascript">
                                $(function(){
                                    $("#back-button").attr("href","/product/detail/id/<?php echo $this->id?>");
                                });
                            </script>
                        <?php }if(!empty($this->country)){?>
                            <script type="text/javascript">
                                $(function(){
                                    $("#back-button").attr("href","/product/detail/id/<?php echo $this->id?>");
                                });
                            </script>
                        <?php }?>
                        <div>
                            <div class="pull-left">
                                <a class="btn btn-outline"><?php echo $this->__('Filter by Price')?></a>
                                <div class="btn-group">
                                    <?php echo $this->partial('partial/select-price.phtml',array('filter' => $this->higher))?>
                                </div>
                                <a class="btn btn-outline"><?php echo $this->__('Filter by recycler country').':'?></a>
                                <div class="btn-group">
                                    <?php echo $this->partial('partial/select-countries.phtml',array('country' => $this->country,'select_name' => 'rcountry'))?>
                                </div>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-outline">
                                    <?php echo $this->__('Export to')?>
                                </a>
                                <div class="btn-group">
                                    <select class="form-control" id="export-format" name="export_format">
                                        <option value="none"><?php echo $this->__('Select format')?></option>
                                        <option value="csv"><?php echo $this->__('CSV')?></option>
                                        <option value="xls"><?php echo $this->__('Excel 2003')?></option>
                                        <option value="xlsx"><?php echo $this->__('Excel 2007')?></option>
                                    </select>
                                </div>
                                <a class="btn btn-warning btn-sm" onclick="exportPriceCompare('<?php echo $product->product_id?>');">
                                    <i class="glyphicon glyphicon-export"></i>
                                    <?php echo $this->__('Export')?>
                                </a>
                            </div>
                        </div>
                        <div class="row clearfix">&nbsp;</div>

                        <table class="display table table-striped table-condensed table-bordered example" id="example" cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                                <th><?php echo $this->__('Recycler Id')?></th>
                                <th><?php echo $this->__('Recycler Name')?></th>
                                <th><?php echo $this->__('Country')?></th>
                                <th><?php echo $this->__('Product Name')?></th>
                                <th><?php echo $this->__('Condition')?></th>
                                <th><?php echo $this->__('Date')?></th>
                                <th><?php echo $this->__('Price')?></th>
                                <th><?php echo $this->__('Price in HKD')?></th>
                                <th><?php echo $this->__('Percentage')?></th>
                                <th><?php echo $this->__('SSA Price')?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if(!empty($this->products)):?>
                                <?php foreach($this->products as $_product):?>
                                    <tr>
                                        <td class="col-checkbox"><input type="checkbox" class="check-item" value="<?php echo $_product->product_id?>"></td>
                                        <td><?php echo $_product->recycler_id?></td>
                                        <td><?php echo $this->recycler()->getName($_product->recycler_id)?></td>
                                        <td><?php echo $this->recycler()->getCountryName($_product->recycler_id)?></td>
                                        <td><?php echo $_product->name;?></td>
                                        <td><?php echo $this->condition($_product->condition_id,false);?></td>
                                        <td><?php echo (!empty($_product->date)) ? date('d-m-Y',$_product->date) : 'N/A';?></td>
                                        <td><?php echo $this->price()->formatCurrency($_product->price,$_product->currency);?></td>
                                        <td><?php echo $this->price()->formatCurrency($this->price()->getExchange($_product->price,$_product->currency),$_product->currency)?></td>
                                        <td><?php echo $this->price()->getPercent($this->price()->getExchange($_product->price,$_product->currency),$product_price).' %'?></td>
                                        <td><?php echo $this->price()->formatCurrency($product_price,'HKD')?></td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="historical-prices">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php if(!empty($product_price)):?>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div class="row form-row">
                                    <div class="col-md-2">
                                        <a class="btn btn-outline"><?php echo $this->__('Set time')?> :</a>
                                    </div>
                                    <div class="col-md-10">
                                        <div class="row">
                                            <div class="pull-left">
                                                <a class="btn btn-outline"> <?php echo $this->__('From')?></a>
                                                <div class="btn-group">
                                                    <div class="input-group input-group-sm">
                                                        <input style="width: 100px" class="form-control datepicker" name="start-time" id="start-time">
                                                    </div>
                                                </div>
                                                <a class="btn btn-outline"><?php echo $this->__('To')?></a>
                                                <div class="btn-group">
                                                    <div class="input-group input-group-sm">
                                                        <input style="width: 100px" class="form-control datepicker" name="end-time" id="end-time">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row form-row">
                                    <div class="col-md-2">
                                        <a class="btn btn-outline"><?php echo $this->__('Search by')?> :</a>
                                    </div>
                                    <div class="col-md-10">
                                        <div class="row ">
                                            <input checked type="radio" name="search" id="highest-price" value="highest">
                                            <span><?php echo $this->__('Highest price')?></span>
                                        </div>
                                        <div class="row form-row">
                                            <input type="radio" name="search" value="country">
                                            <span><?php echo $this->__('Recycler Country')?></span>
                                            <select id="country-select" name="country-select" >
                                                <?php foreach($this->recycler()->getListSelectCountry() as $id=>$country):?>
                                                    <option value="<?php echo $id?>"><?php echo $country?></option>
                                                <?php endforeach;?>
                                            </select>
                                        </div>
                                        <div class="row form-row">
                                            <input type="radio" name="search" value="recycler">
                                            <span><?php echo $this->__('Recycler')?></span>
                                            <select id="recycler-country-select" name="recycler-country-select" onchange="loadRecyclers();">
                                                <?php foreach($this->recycler()->getListSelectCountry() as $id=>$country):?>
                                                    <option value="<?php echo $id?>"><?php echo $country?></option>
                                                <?php endforeach;?>
                                            </select>
                                            <select id="recycler-select" name="recycler-select">
                                                <?php foreach($this->recycler()->getListSelectRecycler() as $recycler_id=>$recycler_name):?>
                                                    <option value="<?php echo $recycler_id?>"><?php echo $recycler_name?></option>
                                                <?php endforeach;?>
                                            </select>
                                        </div>
                                        <div class="row form-row">
                                            <div class="pull-left">
                                                <input type="radio" name="search" value="multi-recycler">
                                                <span><?php echo $this->__('Multi Recyclers')?></span>
                                            </div>
                                            <div class="pull-left" id="multi-select-recyclers">
                                                <select size="10" multiple id="recycler-multi-select" name="recycler-select">
                                                    <?php foreach($this->recycler()->getListSelectRecycler(false) as $recycler_id=>$recycler_name):?>
                                                        <option value="<?php echo $recycler_id?>"><?php echo $recycler_name?></option>
                                                    <?php endforeach;?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="clearfix">&nbsp;</div>
                                <div class="pull-left">
                                    <a onclick="submitHistoricalModelPrice('<?php echo $product->product_id?>');" class="btn btn-sm btn-success">
                                        <i class="glyphicon glyphicon-ok"></i>
                                        <?php echo $this->__('Submit');?>
                                    </a>
                                </div>
                                <div class="pull-right">
                                    <ul class="nav-tabs nav-pills" data-tabs="tabs" id="model-view-tabs">
                                        <li>
                                            <a class="btn btn-sm" data-toggle="tab" href="#chart-view">
                                                <i class="glyphicon glyphicon-stats"></i>
                                                <?php echo $this->__('Chart')?>
                                            </a>
                                        </li>
                                        <li class="active">
                                            <a class="btn btn-sm" data-toggle="tab" href="#table-view">
                                                <i class="glyphicon glyphicon-th"></i>
                                                <?php echo $this->__('Table')?>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                        <div class="clearfix">&nbsp;</div>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <div id="search-result">

                                </div>
                            </div>
                        </div>
                        <?php else:?>
                            <h3><?php echo $this->__('This product does not have SSA Price');?></h3>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>