<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<div class="page-header">
    <div class="pull-left">
        <h3><?php echo $this->__('Models')?></h3>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <div class="pull-left">
        <a class="btn btn-outline"><?php echo $this->__('Filter by Country').':'?></a>
        <div class="btn-group">
            <?php echo $this->partial('partial/select-countries.phtml',array('country' => $this->country))?>
        </div>
        <a class="btn btn-outline"><?php echo $this->__('Filter Recycler Country').':'?></a>
        <div class="btn-group">
            <?php echo $this->partial('partial/select-countries.phtml',array('country' => $this->recycler_country,'select_id' => 'recycler-country-chosen','select_name' => 'recycler_country_chosen'))?>
        </div>
    </div>
    <div class="pull-right">
        <a class="btn btn-success btn-sm" href="<?php echo $this->getUrl('product')?>"><span><?php echo $this->__('Back')?></span></a>
    </div>
    <div class="row clearfix">&nbsp;</div>
    <input type="hidden" value="<?php echo $this->country?>" name="tdm_country" id="tdm-country">
    <input type="hidden" value="<?php echo $this->recycler_country?>" name="recycler_country" id="recycler-country">
    <table class="display table table-striped table-condensed table-bordered withphp" cellpadding="0" cellspacing="0">
        <thead>
        <tr>
            <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
            <th><?php echo $this->__('ID')?></th>
            <th><?php echo $this->__('Name')?></th>
            <th><?php echo $this->__('Condition')?></th>
            <th><?php echo $this->__('Type')?></th>
            <th><?php echo $this->__('Brand')?></th>
            <th><?php echo $this->__('Country')?></th>
            <th><?php echo $this->__('SSA Price')?></th>
            <th><?php echo $this->__('Recycler 1')?></th>
            <th><?php echo $this->__('Price in HKD 1')?></th>
            <th><?php echo $this->__('Percentage 1')?></th>
            <th><?php echo $this->__('Recycler 2')?></th>
            <th><?php echo $this->__('Price in HKD 2')?></th>
            <th><?php echo $this->__('Percentage 2')?></th>
            <th><?php echo $this->__('Recycler 3')?></th>
            <th><?php echo $this->__('Price in HKD 3')?></th>
            <th><?php echo $this->__('Percentage 3')?></th>
            <th class="action3"><?php echo $this->__('Action')?></th>
        </tr>
        </thead>
        <tbody>
        <?php if(count($this->paginator)):?>
            <?php foreach($this->paginator as $row):?>
                <tr>
                    <td class="col-checkbox"><input name="ids[]" type="checkbox" class="check-item" value="<?php echo $row->product_id?>"></td>
                    <td><?php echo $row->product_id?></td>
                    <td><?php echo $row->name?></td>
                    <td><?php echo $this->condition($row->condition_id)?></td>
                    <td><?php echo $this->product_type()->getName($row->type_id)?></td>
                    <td><?php echo $this->product_brand()->getName($row->brand_id)?></td>
                    <td><?php echo $this->country($row->country_id)?></td>
                    <?php
                    $data = array();
                    $ssa_price = $this->product()->getSSAPrice($row->model,$row->condition_id);
                    if(!empty($ssa_price)):
                        ?>
                        <td><?php echo $this->price()->formatCurrency($ssa_price,'HKD')?></td>
                        <?php
                        $recyclerProducts = $this->product()->getTopPriceRecyclerProductByModel($row->model,$row->condition_id,3,$this->recycler_country);
                        if(!empty($recyclerProducts)){
                            foreach($recyclerProducts as $rp){
                                $currentExchange = $this->exchange()->getCurrentExchangeOfCurrency($rp->currency);
                                $priceExchange = ((float) $rp->price )/ $currentExchange;
                                if($ssa_price != 0){
                                    $percentage = (($priceExchange-$ssa_price)/$ssa_price)*100;
                                }else{
                                    $percentage = 'N/A';
                                }
                                $data[] = array(
                                    'recycler' => $this->recycler()->getName($rp->recycler_id),
                                    'price' => $priceExchange,
                                    'percentag' => $percentage,
                                );
                            }
                        }
                    endif;
                    ?>
                    <?php if(!empty($data)):?>
                        <?php $i=0;foreach($data as $item):?>
                            <td><?php echo $item['recycler']?></td>
                            <td><?php echo $this->price()->formatCurrency($item['price'],'HKD')?></td>
                            <td><?php echo (is_numeric($item['percentag'])) ? $this->price()->format($item['percentag']).' %' : $item['percentag'];?></td>
                            <?php $i++;?>
                        <?php endforeach;?>
                        <?php if($i==1):?>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        <?php elseif($i==2):?>
                            <td></td>
                            <td></td>
                            <td></td>
                        <?php endif;?>
                        <?php ?>
                    <?php else:?>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    <?php endif;?>
                    <?php ?>
                    <td class="action3">
                        <a class="btn btn-xs btn-primary btn-edit" href="<?php echo $this->getUrl('product/detail/id/'.$row->product_id)?>">
                            <i class="glyphicon glyphicon-edit"></i>
                            <?php echo $this->__('Detail')?>
                        </a>
                        <a class="btn btn-xs btn-warning btn-edit" href="/product/edit/id/<?php echo $row->product_id?>">
                            <i class="glyphicon glyphicon-edit"></i>
                            <?php echo $this->__('Edit')?>
                        </a>
                        <a onclick="confirmDelete('/product/delete/id/<?php echo $row->product_id?>')" class="btn btn-xs btn-danger btn-delete">
                            <i class="glyphicon glyphicon-trash"></i>
                            <?php echo $this->__('Delete')?>
                        </a>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endif;?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator,
        'Sliding',
        'paginator_style_3', array('route' => 'product-filter-country','country' => $this->country,'recycler_country' => $this->recycler_country)); ?>
</div>