<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<?php $higher = ($this->higher) ? $this->higher : 50;?>
<div class="page-header">
    <div class="pull-left">
        <h3><?php echo $this->translate('Models Filtered')?></h3>
    </div>
    <div class="clearfix"></div>
</div>
<form id="model" action="/product/delete" method="post" enctype="multipart/form-data">
    <div class="row">
        <table class="display table table-striped table-condensed table-bordered example" id="example" cellpadding="0" cellspacing="0">
            <thead>
            <tr>
                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                <th><?php echo $this->translate('Product Id')?></th>
                <th><?php echo $this->translate('Product Name')?></th>
                <th><?php echo $this->translate('Condition')?></th>
                <th><?php echo $this->translate('Product Type')?></th>
                <th><?php echo $this->translate('Brand')?></th>
                <th><?php echo $this->translate('TDM Price in HKD')?></th>
                <th><?php echo $this->translate('Recycler Name')?></th>
                <th><?php echo $this->translate('Recycler Price')?></th>
                <th><?php echo $this->translate('Price in HKD')?></th>
                <th><?php echo $this->translate('Percentage')?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($this->rowset)):?>
                <?php foreach($this->rowset as $_product):?>
                    <?php $data = $this->product()->filterHigherProduct($_product);?>
                    <?php if(!empty($data)):?>
                    <?php ?>
                    <tr>
                        <td class="col-checkbox"><input type="checkbox" class="check-item" value="<?php echo $_product->product_id?>"></td>
                        <td><?php echo $_product->product_id?></td>
                        <td><?php echo $_product->name;?></td>
                        <td><?php echo $this->condition($_product->condition_id,false);?></td>
                        <td><?php echo $this->productType($_product->type_id);?></td>
                        <td><?php echo $this->productBrand($_product->brand_id);?></td>
                        <!--process tdm exchange price here-->
                        <td><?php echo  $this->price()->formatCurrency($data['tdmExchangePrice'],'HKD')?></td>
                        <td><?php echo $this->recycler()->getName($_product->recycler_id)?></td>
                        <td><?php echo $this->price()->formatCurrency($_product->price,$_product->currency);?></td>
                        <td><?php echo $this->price()->formatCurrency($this->price()->getExchange($_product->price,$_product->currency),'HKD')?></td>
                        <td><?php echo $this->price()->format($data['percentage']).' %';?></td>
                    </tr>
                    <?php endif; ?>
                <?php endforeach;?>
            <?php endif;?>
        </table>
    </div>
</form>
