<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/28/13
 */
?>
<?php $startTime = $this->start;?>
<?php $endTime = $this->end?>
<?php $recyclers = $this->recyclers;?>
<?php $entry = $this->entry;?>
<?php if(!$endTime || empty($endTime)):?>
<?php $endTime = time()?>
<?php endif;?>
<div class="pull-right" style="margin-bottom: 15px;">
    <a class="btn">
        <?php echo $this->__('Export to')?>
    </a>
    <div class="btn-group">
        <select class="form-control" id="historical-export-format" name="historical_export_format">
            <option value="none"><?php echo $this->__('Select format')?></option>
            <option value="csv"><?php echo $this->__('CSV')?></option>
            <option value="xls"><?php echo $this->__('Excel 2003')?></option>
            <option value="xlsx"><?php echo $this->__('Excel 2007')?></option>
        </select>
    </div>
    <a class="btn btn-warning btn-sm" onclick="exportHistorical('<?php echo $this->id ?>')">
        <i class="glyphicon glyphicon-export"></i>
        <?php echo $this->__('Export')?>
    </a>
</div>
<?php if($this->search == 'highest'):?>
    <div class="tab-content">
        <div class="tab-pane active" id="table-view">
            <table class="display table table-striped table-condensed table-bordered example2" id="example2" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th class="col-checkbox"><input type="checkbox" class="checkall" name="checkall"></th>
                    <th><?php echo $this->__('Date')?></th>
                    <th><?php echo $this->__('Model Name')?></th>
                    <th><?php echo $this->__('Condition')?></th>
                    <th><?php echo $this->__('Recycler Detail')?></th>
                    <th><?php echo $this->__('SSA Price')?></th>
                    <th><?php echo $this->__('Currency')?></th>
                    <th><?php echo $this->__('Exchange Rate')?></th>
                    <th><?php echo $this->__('Price in HKD')?></th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->products)):?>
                    <?php foreach($this->products as $highest):?>
                    <tr>
                        <td class="col-checkbox"><input class="checkitem" name="product" type="checkbox" value="<?php echo $highest['product_id']?>"></td>
                        <td><?php echo ($highest['time'] != null) ? date('d-m-Y H:i:s',(int)$highest['time']) : 'N/A'?></td>
                        <td><?php echo $this->product()->getRecyclerProductName($highest['product_id'])?></td>
                        <td><?php echo $this->product()->getRecyclerProductCondition($highest['product_id'])?></td>
                        <td><?php echo $this->recycler()->getRecyclerDetail($highest['recycler_id'])?></td>
                        <td><?php echo $this->price()->formatCurrency($highest['price'],$highest['currency'])?></td>
                        <td><?php echo $highest['currency']?></td>
                        <td><?php echo $this->price()->format($highest['exchange_rate'],4)?></td>
                        <td><?php echo $this->price()->formatCurrency($highest['exchange_price'],'HKD')?></td>
                    </tr>
                    <?php endforeach;?>
                <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="chart-view">
            <div class="row clearfix">&nbsp;</div>
            <div id="chart-highest" class="chart-demo" style="min-height: 600px; width:90%;">
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            /*var line1=[['23-May-08', 578.55], ['20-Jun-08', 566.5], ['25-Jul-08', 480.88], ['22-Aug-08', 509.84],
                ['26-Sep-08', 454.13], ['24-Oct-08', 379.75], ['21-Nov-08', 303], ['26-Dec-08', 308.56],
                ['23-Jan-09', 299.14], ['20-Feb-09', 346.51], ['20-Mar-09', 325.99], ['24-Apr-09', 386.15]];*/
            var line1 = new Array();
            <?php if(!empty($this->products)):?>
            <?php foreach($this->products as $highest):?>
            var point = new Array();
            point.push('<?php echo date('d-M-y',$highest['time'])?>');
            point.push(<?php echo $highest['exchange_price']?>);
            line1.push(point);
            <?php endforeach;?>
            console.log(line1);
            var plot100 = $.jqplot('chart-highest', [line1], {
                title:'Historical Price Chart',
                axes:{
                    xaxis:{
                        renderer:$.jqplot.DateAxisRenderer,
                        tickOptions:{
                            formatString:'%b&nbsp;%#d'
                        }
                    },
                    yaxis:{
                        tickOptions:{
                            formatString:'$%.2f'
                        }
                    }
                },
                highlighter: {
                    show: true,
                    sizeAdjust: 7.5
                },
                cursor: {
                    show: false
                }
            });
            <?php endif;?>
            $( 'a[href=#chart-view]' ).on( "click", function() {
                $( 'a[href=#chart-view]').tab('show');
                <?php if(!empty($this->products)):?>
                plot100.replot();
                <?php endif;?>
            });
        });
    </script>
<?php elseif($this->search == 'country'):?>
    <div class="tab-content">
        <div class="tab-pane active" id="table-view">
            <table class="display table table-striped table-condensed table-bordered example2" id="example2" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th class="col-checkbox"><input type="checkbox" class="checkall" name="checkall"></th>
                    <th><?php echo $this->__('Date')?></th>
                    <th><?php echo $this->__('Model Name')?></th>
                    <th><?php echo $this->__('Condition')?></th>
                    <th><?php echo $this->__('Recycler Detail')?></th>
                    <th><?php echo $this->__('Price')?></th>
                    <th><?php echo $this->__('Currency')?></th>
                    <th><?php echo $this->__('Exchange Rate')?></th>
                    <th><?php echo $this->__('Price in HKD')?></th>
                </tr>
                </thead>
                <tbody>
                <?php $data = array();?>
                <?php if(!empty($this->products)):?>
                    <?php foreach($this->products as $product):?>
                        <?php $current_exchange = $this->exchange()->getCurrentExchangeOfCurrency($product->currency);?>
                        <?php $price_in_hkd = ((float) $product->price)/$current_exchange;?>
                        <?php
                        $data[$product->recycler_id][] = array(
                            'price' => $price_in_hkd,
                            'time' => date('Y-m-d',$product->date)
                        );
                        ?>
                        <tr>
                            <td class="col-checkbox"><input class="checkitem" name="product" type="checkbox" value="<?php echo $product->product_id?>"></td>
                            <td><?php echo (!empty($product->date)) ? date('d-m-Y H:i:s',(int)$product->date) : 'N/A'?></td>
                            <td><?php echo $product->model?></td>
                            <td><?php echo $product->condition_name?></td>
                            <td><?php echo $this->recycler()->getRecyclerDetail($product->recycler_id)?></td>
                            <td><?php echo $this->price()->formatCurrency($product->price,$product->currency)?></td>
                            <td><?php echo $product->currency?></td>
                            <td><?php echo $this->price()->format($current_exchange)?></td>
                            <td><?php echo $this->price()->formatCurrency($price_in_hkd,'HKD')?></td>
                        </tr>
                    <?php endforeach;?>
                <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="chart-view">
            <div class="row clearfix">&nbsp;</div>
            <div id="chart-highest" class="chart-demo" style="min-height: 600px; width:90%;">
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function(){
            /**
             * Exchange Rate chart
             */
            <?php if(!empty($data)):?>
            var lines = new Array();
            <?php foreach($data as $line=>$val):?>
            var line<?php echo $line?> = new Array();
            <?php if(!empty($val)):?>
            <?php foreach($val as $index=>$row):?>
            var item<?php echo $index?> = new Array();
            item<?php echo $index?>.push('<?php echo $row['time']?>');
            item<?php echo $index?>.push(<?php echo $row['price']?>);
            line<?php echo $line?>.push(item<?php echo $index?>);
            <?php endforeach;?>
            <?php endif;?>
            lines.push(line<?php echo $line?>);
            <?php endforeach;?>
            var seriesLabels = [
                <?php if(!empty($data)):?>
                <?php $i=0;foreach($data as $line=>$val):?>
                {'label': '<?php echo $this->recycler()->getName($line)?>' },
                <?php endforeach;?>
                <?php endif;?>
            ];
            var plot100 = $.jqplot('chart-highest', lines, {
                title:'Historical Price Chart',
                axes:{
                    xaxis:{
                        renderer:$.jqplot.DateAxisRenderer
                    },
                    yaxis:{
                        tickOptions:{
                            formatString:'%.2f'
                        }
                    }
                },
                series:seriesLabels,
                legend: {
                    show: true,
                    location:'se'
                },
                highlighter: {
                    show: true,
                    sizeAdjust: 10,
                    tooltipContentEditor: function(str, seriesIndex, pointIndex, plot){
                        return seriesLabels[seriesIndex].label + ': ' + str;
                    },
                    tooltipAxes: 'y'
                },
                cursor: {
                    show: false
                }
            });
            <?php endif;?>
            $( 'a[href=#chart-view]' ).on( "click", function() {
                $( 'a[href=#chart-view]').tab('show');
                <?php if(!empty($data)):?>
                plot100.replot();
                <?php endif;?>
            });
        });
    </script>
<?php elseif($this->search == 'recycler' || $this->search == 'multi-recycler'):?>
    <div class="tab-content">
        <div class="tab-pane active" id="table-view">
            <table class="display table table-striped table-condensed table-bordered example2" id="example2" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th class="col-checkbox"><input type="checkbox" class="checkall" name="checkall"></th>
                    <th><?php echo $this->__('Date')?></th>
                    <th><?php echo $this->__('Model Name')?></th>
                    <th><?php echo $this->__('Condition')?></th>
                    <th><?php echo $this->__('Recycler Detail')?></th>
                    <th><?php echo $this->__('Price')?></th>
                    <th><?php echo $this->__('Currency')?></th>
                    <th><?php echo $this->__('Exchange Rate')?></th>
                    <th><?php echo $this->__('Price in HKD')?></th>

                </tr>
                </thead>
                <tbody>
                <?php $data = array();?>
                <?php if(!empty($this->products)):?>
                    <?php foreach($this->products as $product):?>
                        <?php $current_exchange = $this->exchange()->getCurrentExchangeOfCurrency($product->currency);?>
                        <?php $price_in_hkd = ((float) $product->price)/$current_exchange;?>
                        <?php
                        $data[$product->recycler_id][] = array(
                            'price' => $price_in_hkd,
                            'time' => date('Y-m-d',$product->date)
                        );
                        ?>
                        <tr>
                            <td class="col-checkbox"><input class="checkitem" name="product" type="checkbox" value="<?php echo $product->product_id?>"></td>
                            <td><?php echo (!empty($product->date)) ? date('d-m-Y H:i:s',(int)$product->date) : 'N/A'?></td>
                            <td><?php echo $product->model?></td>
                            <td><?php echo $product->condition_name?></td>
                            <td><?php echo $this->recycler()->getRecyclerDetail($product->recycler_id)?></td>
                            <td><?php echo $this->price()->formatCurrency($product->price,$product->currency)?></td>
                            <td><?php echo $product->currency?></td>
                            <td><?php echo $this->price()->format($current_exchange)?></td>
                            <td><?php echo $this->price()->formatCurrency($price_in_hkd,'HKD')?></td>
                        </tr>
                    <?php endforeach;?>
                <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="chart-view">
            <div class="row clearfix">&nbsp;</div>
            <div id="chart-highest" class="chart-demo" style="min-height: 600px; width:90%;">
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function(){
            /**
             * Exchange Rate chart
             */
            <?php if(!empty($data)):?>
            var lines = new Array();
            <?php foreach($data as $line=>$val):?>
            var line<?php echo $line?> = new Array();
            <?php if(!empty($val)):?>
            <?php foreach($val as $index=>$row):?>
            var item<?php echo $index?> = new Array();
            item<?php echo $index?>.push('<?php echo $row['time']?>');
            item<?php echo $index?>.push(<?php echo $row['price']?>);
            line<?php echo $line?>.push(item<?php echo $index?>);
            <?php endforeach;?>
            <?php endif;?>
            lines.push(line<?php echo $line?>);
            <?php endforeach;?>
            var seriesLabels = [
                <?php if(!empty($data)):?>
                <?php $i=0;foreach($data as $line=>$val):?>
                {'label': '<?php echo $this->recycler()->getName($line)?>' },
                <?php endforeach;?>
                <?php endif;?>
            ];
            var plot100 = $.jqplot('chart-highest', lines, {
                title:'Historical Price Chart',
                axes:{
                    xaxis:{
                        renderer:$.jqplot.DateAxisRenderer
                    },
                    yaxis:{
                        tickOptions:{
                            formatString:'%.2f'
                        }
                    }
                },
                series:seriesLabels,
                legend: {
                    show: true,
                    location:'se'
                },
                highlighter: {
                    show: true,
                    sizeAdjust: 10,
                    tooltipContentEditor: function(str, seriesIndex, pointIndex, plot){
                        return seriesLabels[seriesIndex].label + ': ' + str;
                    },
                    tooltipAxes: 'y'
                },
                cursor: {
                    show: false
                }
            });
            <?php endif;?>
            $( 'a[href=#chart-view]' ).on( "click", function() {
                $( 'a[href=#chart-view]').tab('show');
                <?php if(!empty($data)):?>
                plot100.replot();
                <?php endif;?>
            });
        });
    </script>
<?php endif;?>

<script type="text/javascript">
    $(function(){
        $(".checkall").on("click", function () {
            var checkedd = $(this).is(":checked");
            $(".checkitem").prop('checked',checkedd);
        });
        $('.example2').dataTable( {
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [ 0 ] }
            ],
            "aaSorting": [[1, 'asc']],
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "aLengthMenu": [[ 50, 100, 200, 1000 , -1], [ 50, 100, 200, 1000 , "All"]],
            "iDisplayLength": 30,
            "sPaginationType": "full_numbers"
        } );
    });
</script>