<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/28/13
 */
?>
<?php $startTime = $this->start;?>
<?php $endTime = $this->end?>
<?php if(!$endTime || empty($endTime)):?>
<?php $endTime = time()?>
<?php endif;?>
<div class="pull-right" style="margin-bottom: 15px;">
    <a class="btn">
        <?php echo $this->__('Export to')?>
    </a>
    <div class="btn-group">
        <select class="form-control" id="historical-export-format" name="historical_export_format">
            <option value="none"><?php echo $this->__('Select format')?></option>
            <option value="csv"><?php echo $this->__('CSV')?></option>
            <option value="xls"><?php echo $this->__('Excel 2003')?></option>
            <option value="xlsx"><?php echo $this->__('Excel 2007')?></option>
        </select>
    </div>
    <a class="btn btn-warning btn-sm" onclick="exportHistorical('<?php echo $this->id ?>')">
        <i class="glyphicon glyphicon-export"></i>
        <?php echo $this->__('Export')?>
    </a>
</div>
<?php if($this->search == 'highest'):?>
    <div class="tab-content">
        <div class="tab-pane active" id="table-view">
            <table class="display table table-striped table-condensed table-bordered example2" id="example2" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th class="col-checkbox"><input type="checkbox" class="checkall" name="checkall"></th>
                    <th><?php echo $this->__('Date')?></th>
                    <th><?php echo $this->__('Model Name')?></th>
                    <th><?php echo $this->__('Condition')?></th>
                    <th><?php echo $this->__('Recycler Detail')?></th>
                    <th><?php echo $this->__('SSA Price')?></th>
                    <th><?php echo $this->__('Currency')?></th>
                    <th><?php echo $this->__('Exchange Rate')?></th>
                    <th><?php echo $this->__('Price in HKD')?></th>
                    <th><?php echo $this->__('Highest Recycler Price')?></th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->highest)):?>
                    <?php $highest = $this->highest;?>
                    <tr>
                        <td class="col-checkbox"><input class="checkitem" name="product" type="checkbox" value="<?php echo $highest['product_id']?>"></td>
                        <td><?php echo ($highest['time'] != null) ? date('d-m-Y',(int)$highest['time']) : 'N/A'?></td>
                        <td><?php echo $this->product()->getRecyclerProductName($highest['product_id'])?></td>
                        <td><?php echo $this->product()->getRecyclerProductCondition($highest['product_id'])?></td>
                        <td><?php echo $this->recycler()->getRecyclerDetail($highest['recycler_id'])?></td>
                        <td><?php echo $this->price()->formatCurrency($highest['price'],$highest['currency'])?></td>
                        <td><?php echo $highest['currency']?></td>
                        <td><?php echo $this->price()->format($highest['exchange_rate'])?></td>
                        <td><?php echo $this->price()->formatCurrency($highest['exchange_price'],'HKD')?></td>
                        <td><?php echo $this->price()->formatCurrency($highest['exchange_price'],'HKD')?></td>
                    </tr>
                <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="chart-view">
            <div class="row clearfix">&nbsp;</div>
            <div id="chart-highest" class="chart-demo" style="min-height: 600px; width:90%;">
                <?php if(!empty($this->highest)):?>
                <?php $highest = $this->highest;?>
                    <?php
                    $price = (float) $highest['price'];
                    $currency = $highest['currency'];
                    $exchangeRates = $this->exchange()->getExchangeByCurrency($currency,$startTime,$endTime);
                    $exchangeAtStart = $this->exchange()->getCurrentExchangeOfCurrency($currency,$startTime);
                    $exchangeAtEnd = $this->exchange()->getCurrentExchangeOfCurrency($currency,$endTime);
                    $data = array();
                    $data[] = array(
                        'price' => $price*$exchangeAtStart,
                        'time' => date('Y-m-d',$startTime)
                    );
                    $data[] = array(
                        'price' => $price*$exchangeAtEnd,
                        'time' => date('Y-m-d',$endTime)
                    );
                    if(!empty($exchangeRates)){
                        foreach($exchangeRates as $exchange){
                            $rate = (float) $exchange->exchange_rate;
                            $data[] = array(
                                'price' => $price*$rate,
                                'time' => date('Y-m-d',$exchange->time)
                            );
                        }
                    }

                    ?>
                <?php endif;?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function(){
            /**
             * Exchange Rate chart
             */
            <?php if(!empty($data)):?>
            var line1 = new Array();

            <?php foreach($data as $index=>$row):?>
            var item<?php echo $index?> = new Array();
            item<?php echo $index?>.push('<?php echo $row['time']?>');
            item<?php echo $index?>.push(<?php echo $row['price']?>);
            line1.push(item<?php echo $index?>);
            <?php endforeach;?>
            var plot100 = $.jqplot('chart-highest', [line1], {
                title:'Historical Price Chart',
                axes:{
                    xaxis:{
                        renderer:$.jqplot.DateAxisRenderer
                    },
                    yaxis:{
                        tickOptions:{
                            formatString:'%.2f'
                        }
                    }
                },
                highlighter: {
                    show: true,
                    sizeAdjust: 7.5
                },
                cursor: {
                    show: false
                }
            });
            <?php endif;?>
            $( 'a[href=#chart-view]' ).on( "click", function() {
                $( 'a[href=#chart-view]').tab('show');
                <?php if(!empty($data)):?>
                plot100.replot();
                <?php endif;?>
            });
        });
    </script>
<?php elseif($this->search == 'country'):?>
    <div class="tab-content">
        <div class="tab-pane active" id="table-view">
            <table class="display table table-striped table-condensed table-bordered example2" id="example2" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th class="col-checkbox"><input type="checkbox" class="checkall" name="checkall"></th>
                    <th><?php echo $this->__('Date')?></th>
                    <th><?php echo $this->__('Model Name')?></th>
                    <th><?php echo $this->__('Condition')?></th>
                    <th><?php echo $this->__('Recycler Detail')?></th>
                    <th><?php echo $this->__('Price')?></th>
                    <th><?php echo $this->__('Currency')?></th>
                    <th><?php echo $this->__('Exchange Rate')?></th>
                    <th><?php echo $this->__('Price in HKD')?></th>
                    <th><?php echo $this->__('Highest Recycler Price')?></th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->highestInCountry)):?>
                    <?php $highestInCountry = $this->highestInCountry;?>
                    <tr>
                        <td class="col-checkbox"><input class="checkitem" name="product" type="checkbox" value="<?php echo $highestInCountry['product_id']?>"></td>
                        <td><?php echo ($highestInCountry['time'] != null) ? date('d-m-Y',(int)$highestInCountry['time']) : 'N/A'?></td>
                        <td><?php echo $this->product()->getRecyclerProductName($highestInCountry['product_id'])?></td>
                        <td><?php echo $this->product()->getRecyclerProductCondition($highestInCountry['product_id'])?></td>
                        <td><?php echo $this->recycler()->getRecyclerDetail($highestInCountry['recycler_id'])?></td>
                        <td><?php echo $this->price()->formatCurrency($highestInCountry['price'],$highestInCountry['currency'])?></td>
                        <td><?php echo $highestInCountry['currency']?></td>
                        <td><?php echo $this->price()->format($highestInCountry['exchange_rate'])?></td>
                        <td><?php echo $this->price()->formatCurrency($highestInCountry['exchange_price'],'HKD')?></td>
                        <?php if(!empty($this->highest)):?>
                        <?php $highest = $this->highest;?>
                            <td><?php echo $this->price()->formatCurrency($highest['exchange_price'],'HKD')?></td>
                        <?php else:?>
                            <td></td>
                        <?php endif;?>
                    </tr>
                <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="chart-view">
            <div class="row clearfix">&nbsp;</div>
            <div id="chart-highest" class="chart-demo" style="min-height: 600px; width:90%;">
                <?php if(!empty($this->highestInCountry)):?>
                    <?php $highest = $this->highestInCountry;?>
                    <?php
                    $price = (float) $highest['price'];
                    $currency = $highest['currency'];
                    $exchangeRates = $this->exchange()->getExchangeByCurrency($currency,$startTime,$endTime);
                    $exchangeAtStart = $this->exchange()->getCurrentExchangeOfCurrency($currency,$startTime);
                    $exchangeAtEnd = $this->exchange()->getCurrentExchangeOfCurrency($currency,$endTime);
                    $data = array();
                    $data[] = array(
                        'price' => $price*$exchangeAtStart,
                        'time' => date('Y-m-d',$startTime)
                    );
                    $data[] = array(
                        'price' => $price*$exchangeAtEnd,
                        'time' => date('Y-m-d',$endTime)
                    );
                    if(!empty($exchangeRates)){
                        foreach($exchangeRates as $exchange){
                            $rate = (float) $exchange->exchange_rate;
                            $data[] = array(
                                'price' => $price*$rate,
                                'time' => date('Y-m-d',$exchange->time)
                            );
                        }
                    }

                    ?>
                <?php endif;?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function(){
            /**
             * Exchange Rate chart
             */
            <?php if(!empty($data)):?>
            var line1 = new Array();
            <?php foreach($data as $index=>$row):?>
            var item<?php echo $index?> = new Array();
            item<?php echo $index?>.push('<?php echo $row['time']?>');
            item<?php echo $index?>.push(<?php echo $row['price']?>);
            line1.push(item<?php echo $index?>);
            <?php endforeach;?>
            var plot100 = $.jqplot('chart-highest', [line1], {
                title:'Historical Price Chart',
                axes:{
                    xaxis:{
                        renderer:$.jqplot.DateAxisRenderer
                    },
                    yaxis:{
                        tickOptions:{
                            formatString:'%.2f'
                        }
                    }
                },
                highlighter: {
                    show: true,
                    sizeAdjust: 7.5
                },
                cursor: {
                    show: false
                }
            });
            <?php endif;?>
            $( 'a[href=#chart-view]' ).on( "click", function() {
                $( 'a[href=#chart-view]').tab('show');
                <?php if(!empty($data)):?>
                plot100.replot();
                <?php endif;?>
            });
        });
    </script>
<?php elseif($this->search == 'recycler' || $this->search == 'multi-recycler'):?>
    <div class="tab-content">
        <div class="tab-pane active" id="table-view">
            <table class="display table table-striped table-condensed table-bordered example2" id="example2" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th class="col-checkbox"><input type="checkbox" class="checkall" name="checkall"></th>
                    <th><?php echo $this->__('Date')?></th>
                    <th><?php echo $this->__('Model Name')?></th>
                    <th><?php echo $this->__('Condition')?></th>
                    <th><?php echo $this->__('Recycler Detail')?></th>
                    <th><?php echo $this->__('Price')?></th>
                    <th><?php echo $this->__('Currency')?></th>
                    <th><?php echo $this->__('Exchange Rate')?></th>
                    <th><?php echo $this->__('Price in HKD')?></th>
                    <th><?php echo $this->__('Highest Recycler Price')?></th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->highestInRecycler)):?>
                    <?php foreach($this->highestInRecycler as $h):?>
                    <tr>
                        <td class="col-checkbox"><input class="checkitem" name="product" type="checkbox" value="<?php echo $h['product_id']?>"></td>
                        <td><?php echo ($h['time'] != null) ? date('d-m-Y',(int)$h['time']) : 'N/A'?></td>
                        <td><?php echo $this->product()->getRecyclerProductName($h['product_id'])?></td>
                        <td><?php echo $this->product()->getRecyclerProductCondition($h['product_id'])?></td>
                        <td><?php echo $this->recycler()->getRecyclerDetail($h['recycler_id'])?></td>
                        <td><?php echo $this->price()->formatCurrency($h['price'],$h['currency'])?></td>
                        <td><?php echo $h['currency']?></td>
                        <td><?php echo $this->price()->format($h['exchange_rate'])?></td>
                        <td><?php echo $this->price()->formatCurrency($h['exchange_price'],'HKD')?></td>
                        <?php if(!empty($this->highest)):?>
                            <?php $highest = $this->highest;?>
                            <td><?php echo $this->price()->formatCurrency($highest['exchange_price'],'HKD')?></td>
                        <?php else:?>
                            <td></td>
                        <?php endif;?>
                    </tr>
                    <?php endforeach;?>
                <?php endif;?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="chart-view">
            <div class="row clearfix">&nbsp;</div>
            <div id="chart-highest" class="chart-demo" style="min-height: 600px; width:90%;">
                <?php if(!empty($this->highestInRecycler)):?>
                <?php
                    $data = array();
                    $productsExchangeDate = $this->productsExchangeDate;
                    foreach($this->productsExchangePrice as $product_id=>$rateArray){
                        $currency = $this->product()->getRecyclerProductCurrency($product_id);
                        $exchangeAtStart = $this->exchange()->getCurrentExchangeOfCurrency($currency,$startTime);
                        $exchangeAtEnd = $this->exchange()->getCurrentExchangeOfCurrency($currency,$endTime);
                        $price = $this->product()->getRecyclerProductPrice($product_id);
                        $data[$product_id][] = array(
                            'time' => date('Y-m-d',$startTime),
                            'price' => $exchangeAtStart*$price
                        );
                        $data[$product_id][] = array(
                            'time' => date('Y-m-d',$endTime),
                            'price' => $exchangeAtEnd*$price
                        );
                        foreach($rateArray as $key=>$price){
                            $item = array(
                                'time' => date('Y-m-d',$productsExchangeDate[$product_id][$key]),
                                'price' => $price
                            );
                            $data[$product_id][] = $item;
                        }
                    }
                endif;
                ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function(){
            /**
             * Exchange Rate chart
             */
            <?php if(!empty($data)):?>
            var lines = new Array();
            <?php foreach($data as $line=>$val):?>
                var line<?php echo $line?> = new Array();
                <?php if(!empty($val)):?>
                <?php foreach($val as $index=>$row):?>
                var item<?php echo $index?> = new Array();
                item<?php echo $index?>.push('<?php echo $row['time']?>');
                item<?php echo $index?>.push(<?php echo $row['price']?>);
                line<?php echo $line?>.push(item<?php echo $index?>);
                <?php endforeach;?>
                <?php endif;?>
                lines.push(line<?php echo $line?>);
            <?php endforeach;?>
            var seriesLabels = [
                <?php if(!empty($data)):?>
                <?php foreach($data as $line=>$val):?>
                {'label': '<?php echo $this->product()->getRecyclerProductName($line)?>' },
                <?php endforeach;?>
                <?php endif;?>
            ];
            var plot100 = $.jqplot('chart-highest', lines, {
                title:'Historical Price Chart',
                axes:{
                    xaxis:{
                        renderer:$.jqplot.DateAxisRenderer
                    },
                    yaxis:{
                        tickOptions:{
                            formatString:'%.2f'
                        }
                    }
                },
                series:seriesLabels,
                highlighter: {
                    show: true,
                    sizeAdjust: 10,
                    tooltipContentEditor: function(str, seriesIndex, pointIndex, plot){
                        return seriesLabels[seriesIndex].label + ': ' + str;
                    },
                    tooltipAxes: 'y'
                },
                cursor: {
                    show: false
                }
            });
            <?php endif;?>
            $( 'a[href=#chart-view]' ).on( "click", function() {
                $( 'a[href=#chart-view]').tab('show');
                <?php if(!empty($data)):?>
                plot100.replot();
                <?php endif;?>
            });
        });
    </script>
<?php endif;?>

<script type="text/javascript">
    $(function(){
        $(".checkall").on("click", function () {
            var checkedd = $(this).is(":checked");
            $(".checkitem").prop('checked',checkedd);
        });
        $('.example2').dataTable( {
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [ 0 ] }
            ],
            "aaSorting": [[1, 'asc']],
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "sPaginationType": "full_numbers"
        } );
    });
</script>