<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<?php $params = $this->params;?>
<?php
if(isset($params['orderby']) && isset($params['dir']) && $params['orderby'] == 'id' && $params['dir'] == 'desc'){
    $id_class = 'sorting_desc';
}elseif(isset($params['orderby']) && isset($params['dir']) && $params['orderby'] == 'id' && $params['dir'] == 'asc'){
    $id_class = 'sorting_asc';
}elseif(!isset($params['orderby'])){
    $id_class = 'sorting_desc';
}else{
    $id_class = 'sorting';
}
$sort_fields = array(
    'brand' => 'sorting',
    'name' => 'sorting',
    'condition' => 'sorting',
    'type' => 'sorting',
    'country' => 'sorting',
    'ssa_price' => 'sorting'
);
foreach($sort_fields as $field=>$class){
    if(isset($params['orderby']) && isset($params['dir']) && $params['orderby'] == $field && $params['dir'] == 'desc'){
        $sort_fields[$field] = 'sorting_desc';
    }elseif(isset($params['orderby']) && isset($params['dir']) && $params['orderby'] == $field && $params['dir'] == 'asc'){
        $sort_fields[$field] = 'sorting_asc';
    }
}
?>
<div class="page-header">
    <div class="pull-left">
        <h3><?php echo $this->__('Models')?></h3>
    </div>
    <div class="pull-right">
        <a onclick="formConfirm('model');" class="btn btn-danger btn-sm add-item">
            <i class="glyphicon glyphicon-trash"></i>
            <?php echo $this->__('Delete selected') ?>
        </a>
        <a class="btn btn-success btn-sm add-item" href="<?php echo $this->__('product/add')?>">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->__('Add new model')?>
        </a>
    </div>
    <div class="clearfix"></div>
</div>
    <div class="row product-index" id="product-index">
        <div class="row">
            <div class="pull-left">
                <a class="btn">
                    <?php echo $this->__('Import from')?>
                </a>
                <div class="btn-group">
                    <select class="form-control" id="import-format" name="import_format">
                        <option value="none"><?php echo $this->__('Select format')?></option>
                        <option value="csv"><?php echo $this->__('CSV')?></option>
                        <option value="xls"><?php echo $this->__('Excel 2003')?></option>
                        <option value="xlsx"><?php echo $this->__('Excel 2007')?></option>
                    </select>
                </div>
                <a class="btn btn-success btn-sm uploadform">
                    <i class="glyphicon glyphicon-upload"></i>
                    <?php echo $this->__('Import')?>
                </a>
                <a class="btn">
                    <?php echo $this->__('Export to')?>
                </a>
                <div class="btn-group">
                    <select class="form-control" id="export-format" name="export_format">
                        <option value="none"><?php echo $this->__('Select format')?></option>
                        <option value="csv"><?php echo $this->__('CSV')?></option>
                        <option value="xls"><?php echo $this->__('Excel 2003')?></option>
                        <option value="xlsx"><?php echo $this->__('Excel 2007')?></option>
                    </select>
                </div>
                <a class="btn btn-warning btn-sm" onclick="exportProducts()">
                    <i class="glyphicon glyphicon-export"></i>
                    <?php echo $this->__('Export')?>
                </a>

            </div>
            <div class="pull-right">
                <a class="btn btn-primary btn-sm btn-search" id="search-tdm"><?php echo $this->__('Search')?></a>
                <a class="btn btn-danger btn-sm btn-reset-filter" id="reset-filter"><?php echo $this->__('Reset filter')?></a>
            </div>
        </div>
        <div class="row clearfix" style="height: 10px;">&nbsp;</div>
        <div class="row">
            <div class="pull-left">
                <?php $country = (isset($params['tdmcountry'])) ? $params['tdmcountry'] : '';?>
                <?php $rcountry = (isset($params['rcountry'])) ? $params['rcountry'] : '';?>
                <?php $higher = (isset($params['higher'])) ? $params['higher'] : '';?>
                <a class="btn btn-outline"><?php echo $this->__('Filter by Price')?></a>
                <div class="btn-group">
                    <?php echo $this->partial('partial/select-price.phtml',array('filter' => $higher))?>
                </div>
                <a class="btn btn-outline"><?php echo $this->__('Filter TDM Country').':'?></a>
                <div class="btn-group">
                    <?php echo $this->partial('partial/select-countries.phtml',array('country' => $country,'select_name' => 'tdmcountry'))?>
                </div>
                <a class="btn btn-outline"><?php echo $this->__('Filter Recycler Country').':'?></a>
                <div class="btn-group">
                    <?php echo $this->partial('partial/select-countries.phtml',array('country' => $rcountry,'select_id' => 'recycler-country-chosen','select_name' => 'rcountry'))?>
                </div>
                <div class="btn-group">
                    <a class="btn btn-outline"><?php echo $this->__('Filter by Date')?>: <?php echo $this->__('From')?></a>
                    <div class="input-group input-group-sm">
                        <input style="width: 100px" size="50" type="text" class="form-control datepicker2 is_searchable" name="date_from" value="<?php echo (isset($params['date_from'])) ? $params['date_from'] : ''?>">
                    </div>
                </div>
                <div class="btn-group">
                    <a class="btn btn-outline"><?php echo $this->__('To')?>:</a>
                    <div class="input-group input-group-sm">
                        <input style="width: 100px" size="30" type="text" class="form-control datepicker2 is_searchable" name="date_to" value="<?php echo (isset($params['date_to'])) ? $params['date_to'] : ''?>">
                    </div>
                </div>
            </div>
        </div>
        <div class="row clearfix" style="height: 10px;">&nbsp;</div>
        <div class="row">
            <div class="pull-left">

            </div>
            <div class="pull-right">

            </div>
        </div>
        <div class="row clearfix" style="height: 10px;">&nbsp;</div>
        <form id="model" action="<?php echo $this->getUrl('product/delete')?>" method="post" enctype="multipart/form-data">
            <table class="display table table-striped table-condensed table-bordered" cellpadding="0" cellspacing="0">
            <thead>
            <tr>
                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                <th class="<?php echo $id_class;?>"><?php echo $this->__('ID')?></th>
                <th class="<?php echo $sort_fields['brand'];?>"><?php echo $this->__('Brand')?></th>
                <th class="<?php echo $sort_fields['name'];?>"><?php echo $this->__('Name')?></th>
                <th class="<?php echo $sort_fields['condition'];?>"><?php echo $this->__('Condition')?></th>
                <th class="<?php echo $sort_fields['type'];?>"><?php echo $this->__('Type')?></th>
                <th class="<?php echo $sort_fields['country'];?>"><?php echo $this->__('Country')?></th>
                <th class="<?php echo $sort_fields['ssa_price'];?>"><?php echo $this->__('SSA Price')?></th>
                <th class=""><?php echo $this->__('Recycler 1')?></th>
                <th class=""><?php echo $this->__('Price in HKD 1')?></th>
                <th class=""><?php echo $this->__('Percentage 1')?></th>
                <th class=""><?php echo $this->__('Recycler 2')?></th>
                <th class=""><?php echo $this->__('Price in HKD 2')?></th>
                <th class=""><?php echo $this->__('Percentage 2')?></th>
                <th class=""><?php echo $this->__('Recycler 3')?></th>
                <th class=""><?php echo $this->__('Price in HKD 3')?></th>
                <th class=""><?php echo $this->__('Percentage 3')?></th>
                <th class="action3"><?php echo $this->__('Action')?></th>
            </tr>

            </thead>
            <tbody>
            <tr class="tr-search">
                <td>&nbsp;</td>
                <td><div class="input-group-sm"><input type="text" class="form-control is_searchable" value="<?php echo (isset($params['id'])) ? $params['id'] : ''?>" name="id"></div></td>
                <td><div class="input-group-sm"><input type="text" class="form-control is_searchable" value="<?php echo (isset($params['brand'])) ? $params['brand'] : ''?>" name="brand"></div></td>
                <td><div class="input-group-sm"><input type="text" class="form-control is_searchable" value="<?php echo (isset($params['name'])) ? $params['name'] : ''?>" name="name"></div></td>
                <td><div class="input-group-sm"><input type="text" class="form-control is_searchable" value="<?php echo (isset($params['condition'])) ? $params['condition'] : ''?>" name="condition"></div></td>
                <td><div class="input-group-sm"><input type="text" class="form-control is_searchable" value="<?php echo (isset($params['type'])) ? $params['type'] : ''?>" name="type"></div></td>
                <td><div class="input-group-sm"><input type="text" class="form-control is_searchable" value="<?php echo (isset($params['country'])) ? $params['country'] : ''?>" name="country"></div></td>
                <td>
                    <div class="input-group-sm"><input placeholder="<?php echo $this->__('From')?>" type="text" class="form-control is_searchable" value="<?php echo (isset($params['ssa_price_from'])) ? $params['ssa_price_from'] : ''?>" name="ssa_price_from"></div>
                    <div class="input-group-sm"><input placeholder="<?php echo $this->__('To')?>" type="text" class="form-control is_searchable" value="<?php echo (isset($params['ssa_price_to'])) ? $params['ssa_price_to'] : ''?>" name="ssa_price_to"></div>
                </td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="recycler1"></div>--></td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="price1"></div>--></td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="percentage1"></div>--></td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="recycler2"></div>--></td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="price2"></div>--></td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="percentage2"></div>--></td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="recycler3"></div>--></td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="price3"></div>--></td>
                <td><!--<div class="input-group-sm"><input type="text" class="form-control" name="percentage3"></div>--></td>
                <td>&nbsp;</td>
            </tr>
            <?php if(count($this->paginator)):?>
                <?php foreach($this->paginator as $row):?>
                    <tr>
                        <td class="col-checkbox"><input name="ids[]" type="checkbox" class="check-item" value="<?php echo $row->product_id?>"></td>
                        <td><?php echo $row->product_id?></td>
                        <td><?php echo $row->brand_name?></td>
                        <td><?php echo $row->name?></td>
                        <td><?php echo $row->condition_name?></td>
                        <td><?php echo $row->type_name?></td>
                        <td><?php echo $row->country_name?></td>
                        <td><?php echo ((float) $row->ssa_price != 0) ? $this->price()->formatCurrency($row->ssa_price) : 'N/A';?></td>
                        <?php $matching = $this->product()->get_recycler_products_matched($row,$params);?>
                        <?php if(!empty($matching)):?>
                        <?php if(isset($params['date_from']) || isset($params['date_to'])):?>
                                <?php $recycler_products = array();?>
                                <?php $products_price_exchange = array();?>
                                <?php $products_percentage = array();?>
                                <?php $i=0;foreach($matching as $m):?>
                                    <td>
                                        <?php echo $m->recycler_name?><br/>
                                        <?php echo date('d-m-Y H:i:s',$m->date)?>
                                    </td>
                                    <?php $current_exchange = $this->exchange()->getCurrentExchangeOfCurrency($m->currency);?>
                                    <?php $priceExchange = ((float) $m->price )/ $current_exchange;?>
                                    <?php
                                    if($row->ssa_price != 0){
                                        $sub = $priceExchange-$row->ssa_price;
                                        $percentage = $sub/$row->ssa_price;
                                    }else{
                                        $percentage = null;
                                    }
                                    $products_percentage[$m->product_id] = $percentage;
                                    $recycler_products[$m->product_id] = $m;
                                    $products_price_exchange[$m->product_id] = $priceExchange*100;
                                    ?>
                                    <?php $i++?>
                                <?php endforeach;?>
                                <?php asort($products_percentage);?>
                                <?php $top3 = array_slice($products_percentage,0,3);?>
                                <?php foreach($top3 as $id):?>
                                    <?php $recycler_product = $recycler_products[$id];?>
                                    <td><?php echo $this->price()->formatCurrency($products_price_exchange[$id])?></td>
                                    <td><?php echo $products_price_exchange[$id]?></td>
                                <?php endforeach;?>
                                <?php if($i==1):?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php elseif($i==2):?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif;?>
                        <?php else:?>
                        <?php $i=0;foreach($matching as $m):?>
                            <td><?php echo $m->recycler_name?></td>
                            <td><?php echo $this->price()->formatCurrency($m->price_in_hkd)?></td>
                            <td><?php echo $m->percentage?></td>
                            <?php $i++?>
                        <?php endforeach;?>
                            <?php if($i==1):?>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            <?php elseif($i==2):?>
                                <td></td>
                                <td></td>
                                <td></td>
                            <?php endif;?>
                            <?php endif;?>
                        <?php else:?>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        <?php endif;?>
                        <?php ?>
                        <td class="action3">
                            <a class="btn btn-xs btn-primary btn-edit" href="<?php echo $this->getUrl('product/detail/id/'.$row->product_id)?>">
                                <i class="glyphicon glyphicon-edit"></i>
                                <?php echo $this->__('Detail')?>
                            </a>
                            <a class="btn btn-xs btn-warning btn-edit" href="/product/edit/id/<?php echo $row->product_id?>">
                                <i class="glyphicon glyphicon-edit"></i>
                                <?php echo $this->__('Edit')?>
                            </a>
                            <a onclick="confirmDelete('/product/delete/id/<?php echo $row->product_id?>')" class="btn btn-xs btn-danger btn-delete">
                                <i class="glyphicon glyphicon-trash"></i>
                                <?php echo $this->__('Delete')?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php else:?>
                <tr><td colspan="18"><p style="text-align: center;"><strong><?php echo $this->__('No product was found.')?></strong></p></td></tr>
            <?php endif;?>
            </tbody>
        </table>
        </form>
        <?php echo $this->paginationControl($this->paginator,
            'Sliding',
            'paginator_style_4', array('route' => 'product-index','params' => $params)); ?>
    </div>
<div style="display: none">
    <div id="upload-form">
        <form id="import-form" method="post" action="<?php echo $this->getUrl('product/import')?>" enctype="multipart/form-data">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->__('Import Tdm Models')?></h3>
                </div>
                <div class="panel-body">
                    <div class="row form-row">
                        <div class="col-md-3">
                            <div class="control-label"><span><?php echo $this->__('File')?> : </span></div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-control">
                                <input type="file" name="upload_file" id="import-file">
                            </div>
                        </div>
                    </div>
                    <div class="row form-row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9" id="upload-action">
                            <button type="submit" class="btn btn-success btn-sm" id="upload-button">
                                <i class="glyphicon glyphicon-upload"></i>
                                <span><?php echo $this->__('Upload')?></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>