<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/17/13
 */
?>
<div class="page-header">
    <div class="pull-left">
        <h2><?php echo $this->__('Manage Users') ?></h2>
    </div>
    <div class="pull-right">
        <a onclick="formConfirm('user');" class="btn btn-danger btn-sm add-item">
            <i class="glyphicon glyphicon-trash"></i>
            <?php echo $this->__('Delete selected') ?>
        </a>
        <a class="btn btn-success btn-sm add-item" href="/user/add">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->__('Add new user') ?>
        </a>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <form id="user" action="/user/delete" method="post" enctype="multipart/form-data">
        <table class="display table table-striped table-condensed table-bordered" id="example" cellpadding="0" cellspacing="0">
            <thead>
            <tr>
                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                <th><?php echo $this->__('ID')?></th>
                <th><?php echo $this->__('First name')?></th>
                <th><?php echo $this->__('Last name')?></th>
                <th><?php echo $this->__('Username')?></th>
                <th><?php echo $this->__('Email')?></th>
                <th><?php echo $this->__('Created at')?></th>
                <th><?php echo $this->__('Status')?></th>
                <th class="action4"><?php echo $this->__('Action')?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($this->users)):?>
                <?php foreach($this->users as $row):?>
                    <tr>
                        <td class="col-checkbox"><input name="ids[]" type="checkbox" class="check-item" value="<?php echo $row->id?>"></td>
                        <td><?php echo $row->id?></td>
                        <td><?php echo $row->first_name?></td>
                        <td><?php echo $row->last_name?></td>
                        <td><?php echo $row->username?></td>
                        <td><?php echo $row->email?></td>
                        <td><?php echo date('Y-m-d H:i:s',$row->created_at)?></td>
                        <td><?php echo ((int)$row->status == 1) ? 'Activated' : 'Disabled';?></td>
                        <td class="action4">
                            <a class="btn btn-xs btn-primary btn-info" href="/user/view-log/id/<?php echo $row->id?>">
                                <i class="glyphicon glyphicon-book"></i>
                                <?php echo $this->__('View log') ?>
                            </a>
                            <a class="btn btn-xs btn-primary btn-edit" href="/user/detail/id/<?php echo $row->id?>">
                                <i class="glyphicon glyphicon-edit"></i>
                                <?php echo $this->__('Edit') ?>
                            </a>
                            <a onclick="confirmDelete('/user/delete/id/<?php echo $row->id?>')" class="btn btn-xs btn-danger btn-delete" >
                                <i class="glyphicon glyphicon-trash"></i>
                                <?php echo $this->__('Delete') ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
        </table>
    </form>
</div>