<div class="page-header">
    <h3><?php echo $this->translate('Dashboard');?></h3>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-md-5">
            <div class="row">
                <div class="col-md-8">
                    <h4><?php echo $this->translate('Last exchange rate')?></h4>

                    <table class="table table-striped table-condensed table-bordered">
                        <tbody>
                        <?php $lastExchange = $this->admin()->getLastExchange();?>
                        <?php if(!empty($lastExchange)):?>
                        <?php foreach($lastExchange as $row):?>
                            <tr>
                                <td><?php echo $row->currency?></td>
                                <td><?php echo $row->exchange_rate?></td>
                            </tr>
                        <?php endforeach;?>
                        <?php endif;?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="table-bordered">
                    <div class="col-md-12">
                        <h4><?php echo $this->translate('New added TDM\'s product');?></h4>
                        <table class="table table-striped table-condensed table-bordered" id="last-tdm">
                            <thead>
                            <th>Name</th>
                            <th>Brand</th>
                            <th>Type</th>
                            </thead>
                            <tbody>
                            <?php $lastTdmProducts = $this->admin()->getLastTdmProducts();?>
                            <?php if(!empty($lastTdmProducts)):?>
                                <?php foreach($lastTdmProducts as $product):?>
                                    <tr onclick="window.location.assign('/product/detail/id/<?php echo $product->product_id?>')">
                                        <td><?php echo $product->name;?></td>
                                        <td><?php echo $this->productBrand($product->brand_id)?></td>
                                        <td><?php echo $this->productType($product->type_id)?></td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="table-bordered">
                    <div class="col-md-12">
                        <h4><?php echo $this->translate('New added recycler information');?></h4>
                        <table class="table table-striped table-condensed table-bordered" id="last-recycler">
                            <thead>
                            <th>Country</th>
                            <th>Recycler</th>
                            </thead>
                            <tbody>
                            <?php $lastRecyclers = $this->admin()->getLastRecyclers();?>
                            <?php if(!empty($lastRecyclers)):?>
                            <?php foreach($lastRecyclers as $recycler):?>
                                <tr onclick="window.location.assign('/recycler/detail/id/<?php echo $recycler->recycler_id?>')">
                                    <td><?php echo $this->country($recycler->country_id)?></td>
                                    <td><?php echo $recycler->name;?></td>
                                </tr>
                            <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>
        <div class="col-md-7">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><?php echo $this->translate('Welcome to Product Model System');?></h4>
                </div>
                <div class="panel-body">
                    Right now
                    <br/>
                    <ul>
                        <li><?php echo $this->admin()->getTotalRecycler()?> recyclers </li>
                        <li><?php echo $this->admin()->getTotalTdmProduct()?> TDM's products</li>
                        <li><?php echo $this->admin()->getTotalRecyclerProduct()?> Recycler's products</li>
                    </ul>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <span>Popular product model price fluctuation diagram</span>
                    <div id="chart-demo" class="chart-demo">
                        <div id="chart-dashboard">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$popular = $this->popular;
if(!empty($popular['products'])){
    $start = \DateTime::createFromFormat('d-m-Y',$popular['start']);
    $startTime = $start->getTimestamp();
    if($this->end == ''){
        $endTime = time();
    }else{
        $end = \DateTime::createFromFormat('d-m-Y',$popular['end']);
        $endTime = $end->getTimestamp();
    }
    $data = array();
    foreach($popular['products'] as $_p){
        $currency = $this->product()->getTdmProductCurrency($_p);
        $price = $this->product()->getTdmProductPrice($_p);
        $exchangeAtStart = $this->exchange()->getCurrentExchangeOfCurrency($currency,$startTime);
        $exchangeAtEnd = $this->exchange()->getCurrentExchangeOfCurrency($currency,$endTime);
        $exchangeRates = $this->exchange()->getExchangeByCurrency($currency,$startTime,$endTime);

        $data[$_p][] = array(
            'price' => $price*$exchangeAtStart,
            'time' => date('Y-m-d',$startTime)
        );
        $data[$_p][] = array(
            'price' => $price*$exchangeAtEnd,
            'time' => date('Y-m-d',$endTime)
        );
        if(!empty($exchangeRates)){
            foreach($exchangeRates as $exchange){
                $rate = (float) $exchange->exchange_rate;
                $data[$_p][] = array(
                    'price' => $price*$rate,
                    'time' => date('Y-m-d',$exchange->time)
                );
            }
        }
    }
    ?>
    <script type="text/javascript">
        $(function(){
            /**
             * Exchange Rate chart
             */
                <?php if(!empty($data)):?>
            var lines = new Array();
            <?php foreach($data as $line=>$val):?>
            var line<?php echo $line?> = new Array();
            <?php if(!empty($val)):?>
            <?php foreach($val as $index=>$row):?>
            var item<?php echo $index?> = new Array();
            item<?php echo $index?>.push('<?php echo $row['time']?>');
            item<?php echo $index?>.push(<?php echo $row['price']?>);
            line<?php echo $line?>.push(item<?php echo $index?>);
            <?php endforeach;?>
            <?php endif;?>
            lines.push(line<?php echo $line?>);
            <?php endforeach;?>
            var seriesLabels = [
                <?php if(!empty($data)):?>
                <?php foreach($data as $line=>$val):?>
                {'label': '<?php echo $this->product()->getRecyclerProductName($line)?>' },
                <?php endforeach;?>
                <?php endif;?>
            ];
            var plot100 = $.jqplot('chart-dashboard', lines, {
                title:'Popular Products',
                axes:{
                    xaxis:{
                        renderer:$.jqplot.DateAxisRenderer
                    },
                    yaxis:{
                        tickOptions:{
                            formatString:'%.2f'
                        }
                    }
                },
                series:seriesLabels,
                highlighter: {
                    show: true,
                    sizeAdjust: 10,
                    tooltipContentEditor: function(str, seriesIndex, pointIndex, plot){
                        return seriesLabels[seriesIndex].label + ': ' + str;
                    },
                    tooltipAxes: 'y'
                },
                cursor: {
                    show: false
                }
            });
            <?php endif;?>
        });
    </script>
<?php
}

?>