<div class="page-header">
    <h3><?php echo $this->translate('Dashboard');?></h3>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="col-md-5">
            <div class="row">
                <div class="col-md-8">
                    <h4><?php echo $this->translate('Last exchange rate')?></h4>
                    <table class="table table-striped table-condensed table-bordered">
                        <tbody>
                        <tr><td>Currency 1</td></tr>
                        <tr><td>Currency 2</td></tr>
                        <tr><td>Currency 3</td></tr>
                        <tr><td>Currency 5</td></tr>
                        <tr><td>Currency 4</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="table-bordered">
                    <div class="col-md-12">
                        <h4><?php echo $this->translate('New added product');?></h4>
                        <table class="table table-striped table-condensed table-bordered">
                            <thead>
                            <th>Type</th>
                            <th>Brand</th>
                            <th>Name</th>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                                <td>Data 1</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                                <td>Data 1</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                                <td>Data 1</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                                <td>Data 1</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                                <td>Data 1</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                                <td>Data 1</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="table-bordered">
                    <div class="col-md-12">
                        <h4><?php echo $this->translate('New added recycler information');?></h4>
                        <table class="table table-striped table-condensed table-bordered">
                            <thead>
                            <th>Country</th>
                            <th>Recycler</th>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>12</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>
        <div class="col-md-7">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><?php echo $this->translate('Welcome to Product Model System');?></h4>
                </div>
                <div class="panel-body">
                    Right now
                    <br/>
                    <ul>
                        <li>10 recyclers </li>
                        <li>10 products model</li>
                    </ul>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <span>Popular product model price fluctuation diagram</span>
                    <div id="chart-demo" class="chart-demo">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>