<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/13/13
 */
?>
<div class="page-header">
    <div class="pull-left">
        <h3>TDM Model</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-success btn-sm add-item" href="/model/add">
            <i class="glyphicon glyphicon-plus"></i>
            Add new model
        </a>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <div class="pull-left">
        <a class="btn btn-outline">Notice</a>
        <div class="btn btn-default">
            Price higher than 50%(xx)
        </div>
    </div>
    <div class="pull-right">
        <a class="btn">
            Export to
        </a>
        <div class="btn-group">
            <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
                Data format <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a>CSV</a></li>
                <li><a>Excel</a></li>
            </ul>
        </div>
        <a class="btn btn-warning btn-sm">
            <i class="glyphicon glyphicon-export"></i>
            Export
        </a>
        <a class="btn btn-default btn-sm">
            <i class="glyphicon glyphicon-refresh"></i>
            Reset filter
        </a>
    </div>
    <div class="row clearfix">&nbsp;</div>
    <table class="display table table-striped table-condensed table-bordered" id="example" cellpadding="0" cellspacing="0">
        <thead>
        <tr>
            <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
            <th><?php echo $this->translate('ID')?></th>
            <th><?php echo $this->translate('Name')?></th>
            <th><?php echo $this->translate('Type')?></th>
            <th><?php echo $this->translate('Brand')?></th>
            <th><?php echo $this->translate('Recycler 1')?></th>
            <th><?php echo $this->translate('Price 1')?></th>
            <th><?php echo $this->translate('Percentage 1')?></th>
            <th><?php echo $this->translate('Recycler 2')?></th>
            <th><?php echo $this->translate('Price 2')?></th>
            <th><?php echo $this->translate('Percentage 2')?></th>
            <th><?php echo $this->translate('Recycler 3')?></th>
            <th><?php echo $this->translate('Price 3')?></th>
            <th><?php echo $this->translate('Percentage 3')?></th>
        </tr>
        </thead>
        <tbody>
        <tr onclick="goToModelDetail();">
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>1</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr onclick="goToModelDetail();">
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>2</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr onclick="goToModelDetail();">
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>3</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr onclick="goToModelDetail();">
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>4</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>5</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>6</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>7</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>8</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>9</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>10</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>11</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>12</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="1"></td>
            <td>13</td>
            <td>Admin</td>
            <td>Vietnam</td>
            <td>admin2@mail.com</td>
            <td>09-13-2014</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
            <th><input type="hidden"></th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
            <th>
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control search_init" />
                </div>
            </th>
        </tr>
        </tfoot>
    </table>
</div>