<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/12/13
 */
?>
<div class="page-header">
    <h2><?php echo $this->translate('Dashboard')?></h2>
    <div class="row">
        <div class="col-md-1">&nbsp;</div>
        <div class="col-md-6">
            <table class="table table-striped table-bordered table-condensed">
                <tbody>
                <tr>
                    <td><b>Total Students</b></td>
                    <td>8</td>
                </tr>
                <tr>
                    <td><b>Total Courses</b></td>
                    <td>3</td>
                </tr>
                <tr>
                    <td><b>Total Lessons</b></td>
                    <td>4</td>
                </tr>
                <tr>
                    <td><b>Total Schools</b></td>
                    <td>5</td>
                </tr>

                </tbody>
            </table>
            <div class="clearfix">
                <br/>
            </div>
            <h3>Payable Invoices</h3>
            <table class="table table-striped table-bordered table-condensed">

                <thead>
                <tr>
                    <th>Invoice Id</th>
                    <th>Student Name</th>
                    <th>Due Date</th>
                    <th>Total Fees</th>
                    <th>Discount</th>
                    <th>Payment Status</th>

                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>8</td>
                    <td>John Doe</td>
                    <td>31-08-2013</td>
                    <td>120.00</td>
                    <td>10.00</td>
                    <td><span class="label label-warning">Payable</span></td>




                </tr>
                <tr>
                    <td>7</td>
                    <td>John Doe</td>
                    <td>22-08-2013</td>
                    <td>120.00</td>
                    <td>30.00</td>
                    <td><span class="label label-warning">Payable</span></td>




                </tr>
                <tr>
                    <td>6</td>
                    <td>John Doe</td>
                    <td>31-08-2013</td>
                    <td>120.00</td>
                    <td>20.00</td>
                    <td><span class="label label-warning">Payable</span></td>




                </tr>
                <tr>
                    <td>5</td>
                    <td>John Doe</td>
                    <td>31-08-2013</td>
                    <td>120.00</td>
                    <td>20.00</td>
                    <td><span class="label label-warning">Payable</span></td>




                </tr>
                <tr>
                    <td>4</td>
                    <td>John Doe</td>
                    <td>20-08-2013</td>
                    <td>120.00</td>
                    <td>0.00</td>
                    <td><span class="label label-warning">Payable</span></td>




                </tr>
                <tr>
                    <td>3</td>
                    <td>Jonny Alex</td>
                    <td>31-08-2013</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td><span class="label label-warning">Payable</span></td>




                </tr>
                <tr>
                    <td>2</td>
                    <td>James William</td>
                    <td>01-07-2013</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td><span class="label label-warning">Payable</span></td>




                </tr>

                </tbody>
            </table>
        </div>
    </div>

</div>