<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/12/13
 */
?>
<div class="page-header">
    <h2><?php echo $this->translate('Manage Users')?></h2>
</div>
<div class="row">
    <div class="text-right">
        <a class="btn btn-default btn-sm">
            <i class="glyphicon glyphicon-refresh"></i>
            <?php echo $this->translate('Refresh')?>
        </a>
        <a class="btn btn-success btn-sm">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->translate('New')?>
        </a>
    </div>
    <div class="row">&nbsp;</div>
<table class="display table table-striped table-condensed example" id="example" cellpadding="0" cellspacing="0" border="0">
<thead>
<tr>
    <th>#</th>
    <th><?php echo $this->translate('User Id')?></th>
    <th><?php echo $this->translate('First Name')?></th>
    <th><?php echo $this->translate('Last Name')?></th>
    <th><?php echo $this->translate('Email')?></th>
    <th><?php echo $this->translate('Action')?></th>
</tr>
</thead>
<tbody>
<tr>
    <td>1</td>
    <td>1</td>
    <td>Admin</td>
    <td>User</td>
    <td>admin@mail.com</td>
    <td>
        <a class="btn btn-xs btn-primary btn-edit">
            <i class="glyphicon glyphicon-edit"></i>
            <?php echo $this->translate('Edit')?>
        </a>
        <a class="btn btn-xs btn-danger btn-delete">
            <i class="glyphicon glyphicon-trash"></i>
            <?php echo $this->translate('Delete')?>
        </a>
    </td>
</tr>
<tr>
    <td>2</td>
    <td>2</td>
    <td>Admin</td>
    <td>User2</td>
    <td>admin2@mail.com</td>
    <td>
        <a class="btn btn-xs btn-primary btn-edit">
            <i class="glyphicon glyphicon-edit"></i>
            <?php echo $this->translate('Edit')?>
        </a>
        <a class="btn btn-xs btn-danger btn-delete">
            <i class="glyphicon glyphicon-trash"></i>
            <?php echo $this->translate('Delete')?>
        </a>
    </td>
</tr>
<tr>
    <td>3</td>
    <td>3</td>
    <td>Admin</td>
    <td>User3</td>
    <td>admin3@mail.com</td>
    <td>
        <a class="btn btn-xs btn-primary btn-edit">
            <i class="glyphicon glyphicon-edit"></i>
            <?php echo $this->translate('Edit')?>
        </a>
        <a class="btn btn-xs btn-danger btn-delete">
            <i class="glyphicon glyphicon-trash"></i>
            <?php echo $this->translate('Delete')?>
        </a>
    </td>
</tr>
<tr>
    <td>4</td>
    <td>4</td>
    <td>Admin</td>
    <td>User4</td>
    <td>admin4@mail.com</td>
    <td>
        <a class="btn btn-xs btn-primary btn-edit">
            <i class="glyphicon glyphicon-edit"></i>
            <?php echo $this->translate('Edit')?>
        </a>
        <a class="btn btn-xs btn-danger btn-delete">
            <i class="glyphicon glyphicon-trash"></i>
            <?php echo $this->translate('Delete')?>
        </a>
    </td>
</tr>
</tbody>
<tfoot>
<tr>
    <th><input type="text" name="search_engine" value="<?php echo $this->translate('Search ')?>#" class="search_init" /></th>
    <th><input type="text" name="search_browser" value="<?php echo $this->translate('Search users id')?>" class="search_init" /></th>
    <th><input type="text" name="search_platform" value="<?php echo $this->translate('Search first name')?>" class="search_init" /></th>
    <th><input type="text" name="search_version" value="<?php echo $this->translate('Search last name')?>" class="search_init" /></th>
    <th><input type="text" name="search_grade" value="<?php echo $this->translate('Search email')?>" class="search_init" /></th>
    <th></th>
</tr>
</tfoot>
</table>
</div>