<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/10/13
 */
return array(
    'NO_DATA'                       => 'No data existed',
    'USER_INSERT_FAIL'              => 'Adding user was failure',
    'INSERT_SUCCESS'                => 'Inserted successfully',
    'UPDATE_SUCCESS'                => 'Updated successfully',
    'DELETE_SUCCESS'                => 'Deleted successfully',
    'INSERT_FAIL'                   => 'Insert fail',
    'UPDATE_FAIL'                   => 'Update fail',
    'DELETE_FAIL'                   => 'Delete fail',
    'EXPORT_SUCCESS'                => 'Export success',
    'EXPORT_FAIL'                   => 'Export fail',
    'ACCOUNT_EXIST'                 => 'User account existed',
    'EMAIL_EXIST'                   => 'This Email was used',
    'PASSWORD_NOT_EMPTY'            => 'Password can not be empty',
    'RECYCLER_NAME_NOT_EMPTY'       => 'You must input Recycler name',
    'PRODUCT_NAME_NOT_EMPTY'        => 'Product name can not be empty',
    'PRODUCT_BRAND_NOT_EMPTY'       => 'Product brand can not be empty',
    'MODEL_NOT_EMPTY'               => 'Model can not be empty',
    'PRODUCT_PRICE_NOT_EMPTY'       => 'Product Price can not be empty',
    'PRODUCT_PRICE_NOT_VALID'       => 'Product Price is not valid',
    'UPLOAD_SUCCESS'                => 'Uploaded successfully',
    'COUNTRY_NAME_NOT_EMPTY'        => 'Country name can not be empty',
    'COUNTRY_NAME_EXIST'            => 'Country name existed',
    'CURRENCY_NOT_EMPTY'            => 'Currency can not be empty',
    'EXCHANGE_RATE_NOT_EMPTY'       => 'Exchange rate can not be empty',
    'MUST_SELECT_CURRENCY'          => 'Please select the currency',
    'CONDITION_NAME_NOT_EMPTY'      => 'Condition name can not be empty',
    'CONDITION_NAME_EXIST'          => 'Condition name existed',
    'TYPE_NAME_NOT_EMPTY'           => 'Type name can not be empty',
    'TYPE_NAME_EXIST'               => 'Type name existed',
    'BRAND_NAME_NOT_EMPTY'          => 'Brand name can not be empty',
    'BRAND_NAME_EXIST'              => 'Brand name existed',
    'PRODUCT_BRAND_NOT_SELECTED'    => 'You must select a brand',
    'COUNTRY_NOT_SELECTED'          => 'You must select a country',
    'PRODUCT_TYPE_NOT_SELECTED'     => 'You must select product type',
    'FORMAT_EXPORT_INVALID'         => 'Format of export file is invalid',
    'FORMAT_IMPORT_INVALID'         => 'Format of import file is invalid',
    'RESOURCE_NAME_NOT_EMPTY'       => 'Resource name can not be empty',
    'PATH_EXIST'                    => 'Resource path existed',
    'ROLE_NAME_NOT_EMPTY'           => 'Role name can not be empty',
    'ROLE_NAME_EXISTED'             => 'Role name existed',
    'RESOURCE_GROUP_NOT_SELECTED'   => 'Please select resource group',
    'RECYCLER_EMAIL_NOT_EMPTY'      => 'Recycler email can not be empty',
    'RECYCLER_EMAIL_INVALID'        => 'Recycler email is invalid',
    'SYMBOL_NOT_EMPTY'              => 'Symbol can not be empty',
);