<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/10/13
 */
return array(
    'NO_DATA'                       => 'No data existed',
    'USER_INSERT_FAIL'              => 'Adding user fail',
    'INSERT_SUCCESS'                => 'Insert success',
    'UPDATE_SUCCESS'                => 'Update success',
    'DELETE_SUCCESS'                => 'Delete success',
    'INSERT_FAIL'                   => 'Insert fail',
    'UPDATE_FAIL'                   => 'Update fail',
    'DELETE_FAIL'                   => 'Delete fail',
    'EXPORT_SUCCESS'                => 'Export success',
    'EXPORT_FAIL'                   => 'Export fail',
    'ACCOUNT_EXIST'                 => 'User account existed',
    'EMAIL_EXIST'                   => 'Email existed',
    'PASSWORD_NOT_EMPTY'            => 'Password does not empty',
    'RECYCLER_NAME_NOT_EMPTY'       => 'Recycler name does not empty',
    'PRODUCT_NAME_NOT_EMPTY'        => 'Product name does not empty',
    'PRODUCT_BRAND_NOT_EMPTY'       => 'Product brand does not empty',
    'MODEL_NOT_EMPTY'               => 'Model does not empty',
    'PRODUCT_PRICE_NOT_EMPTY'       => 'Product Price does not empty',
    'PRODUCT_PRICE_NOT_VALID'       => 'Product Price does not valid',
    'UPLOAD_SUCCESS'                => 'Upload success',
    'COUNTRY_NAME_NOT_EMPTY'        => 'Country name does not empty',
    'COUNTRY_NAME_EXIST'            => 'Country name existed',
    'CURRENCY_NOT_EMPTY'            => 'Currency does not empty',
    'EXCHANGE_RATE_NOT_EMPTY'       => 'Exchange rate does not empty',
    'MUST_SELECT_CURRENCY'          => 'Please select the currency',
    'CONDITION_NAME_NOT_EMPTY'      => 'Condition name does not empty',
    'CONDITION_NAME_EXIST'          => 'Condition name existed',
    'TYPE_NAME_NOT_EMPTY'           => 'Type name does not empty',
    'TYPE_NAME_EXIST'               => 'Type name existed',
    'BRAND_NAME_NOT_EMPTY'          => 'Brand name does not empty',
    'BRAND_NAME_EXIST'              => 'Brand name existed',
    'PRODUCT_BRAND_NOT_SELECTED'    => 'You must select brand',
    'COUNTRY_NOT_SELECTED'          => 'You must select country',
    'PRODUCT_TYPE_NOT_SELECTED'     => 'You must select product type',
    'FORMAT_EXPORT_INVALID'         => 'Format of export file invalid',
    'FORMAT_IMPORT_INVALID'         => 'Format of import file invalid',
    'RESOURCE_NAME_NOT_EMPTY'       => 'Resource name does not empty',
    'PATH_EXIST'                    => 'Resource path existed',
    'ROLE_NAME_NOT_EMPTY'           => 'Role name does not empty',
    'ROLE_NAME_EXISTED'             => 'Role name existed',
    'RESOURCE_GROUP_NOT_SELECTED'   => 'Please select resource group',
);