<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/12/13
 */
?>
<?php
$role = $this->menu()->getRole();
$groups = $this->menu()->getResourceGroups();
?>
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <?php if($role == 'super_admin'):?>
                <ul class="nav navbar-nav nav-top">
                    <li class="">
                        <a href="/index/" class="nav-header">
                            Dashboard </a>
                    </li>
                    <li class="">
                        <a href="/recycler/" class="nav-header">
                            Recycler </a>
                    </li>
                    <li class="">
                        <a href="/product/" class="nav-header">
                            TDM Model </a>
                    </li>
                    <li class="dropdown ">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <span>Exchange Rate</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/exchange/">
                                    Historical Exchange Date </a>
                            </li>
                            <li>
                                <a href="/exchange/update/">
                                    Update Exchange Rate </a>
                            </li>
                        </ul>
                    </li>

                    <li class="dropdown ">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <span>System</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/user/">
                                    Manage Users </a>
                            </li>
                            <li>
                                <a href="/role/">
                                    Manage Roles </a>
                            </li>
                            <li>
                                <a href="/resource/">
                                    Manage Resources </a>
                            </li>
                            <li>
                                <a href="/exchange/country/">
                                    Manage Countries </a>
                            </li>
                            <li>
                                <a href="/condition/tdm/">
                                    Condition Management </a>
                            </li>
                            <li>
                                <a href="/product/type/">
                                    Product Type Management </a>
                            </li>
                            <li>
                                <a href="/product/brand/">
                                    Brand Management </a>
                            </li>
                            <li>
                                <a href="/product/popular/">
                                    Popular Product </a>
                            </li>
                        </ul>
                    </li>

                    <li class="">
                        <a href="/help/" class="nav-header">
                            Help </a>
                    </li>
                </ul>
            <?php else:?>
                <ul class="nav navbar-nav nav-top">
                    <li class="">
                        <a href="/index/" class="nav-header">
                            Dashboard </a>
                    </li>
                    <?php if(!empty($groups)):?>
                    <?php if(in_array('recycler',$groups)):?>
                        <li class="">
                            <a href="/recycler/" class="nav-header">
                                Recycler </a>
                        </li>
                    <?php endif;?>
                    <?php if(in_array('tdm-product',$groups)):?>
                        <li class="">
                            <a href="/product/" class="nav-header">
                                TDM Model </a>
                        </li>
                    <?php endif;?>
                    <?php if(in_array('exchange',$groups)):?>
                        <li class="dropdown ">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                <span>Exchange Rate</span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/exchange/">
                                        Historical Exchange Date </a>
                                </li>
                                <li>
                                    <a href="/exchange/update/">
                                        Update Exchange Rate </a>
                                </li>
                            </ul>
                        </li>
                    <?php endif;?>
                    <?php if(in_array('user',$groups) || in_array('role',$groups) || in_array('resource',$groups)
                            || in_array('country',$groups) || in_array('tdm-condition',$groups)
                            || in_array('product-type',$groups) || in_array('brand',$groups) || in_array('tdm-product',$groups)):?>
                        <li class="dropdown ">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                <span>System</span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <?php if(in_array('user',$groups)):?>
                                    <li>
                                        <a href="/user/">
                                            Manage Users </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('role',$groups)):?>
                                    <li>
                                        <a href="/role/">
                                            Manage Roles </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('resource',$groups)):?>
                                    <li>
                                        <a href="/resource/">
                                            Manage Resources </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('country',$groups)):?>
                                    <li>
                                        <a href="/exchange/country/">
                                            Manage Countries </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('tdm-condition',$groups)):?>
                                    <li>
                                        <a href="/condition/tdm/">
                                            TDM Condition Management </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('product-type',$groups)):?>
                                    <li>
                                        <a href="/product/type/">
                                            Product Type Management </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('brand',$groups)):?>
                                    <li>
                                        <a href="/product/brand/">
                                            Brand Management </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('tdm-product',$groups)):?>
                                    <li>
                                        <a href="/product/popular/">
                                            Popular Product </a>
                                    </li>
                                <?php endif;?>
                            </ul>
                        </li>
                    <?php endif;?>
                    <?php endif;?>

                    <li class="">
                        <a href="/help/" class="nav-header">
                            Help </a>
                    </li>
                </ul>
            <?php endif;?>

        </div><!-- /.navbar-collapse -->
    </div>
</nav>