<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 10/17/13
 */
?>
<?php $select_id = (!empty($this->select_id) ? $this->select_id : 'country-chosen')?>
<?php $select_name = (!empty($this->select_name) ? $this->select_name : 'country_chosen')?>
<?php $country = (int) $this->country;?>
<?php $countries = $this->product()->getAvailableCountries()?>
<?php if(!empty($countries)):?>
    <select name="<?php echo $select_name ?>" class="chosen-select form-control is_searchable" id="<?php echo $select_id?>" data-placeholder="<?php echo $this->__('Choose a country')?>">
        <option></option>
        <option value="reset"><?php echo $this->__('Reset filter')?></option>
    <?php foreach($countries as $row):?>
        <option <?php if($country == (int)$row->country_id){echo 'selected';}?> value="<?php echo $row->country_id?>"><?php echo $row->name;?></option>
    <?php endforeach;?>
    </select>
<?php endif;?>