<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/17/13
 */
?>
<div class="page-header">
    <div class="pull-left">
        <h2>Add User</h2>
    </div>
    <div class="pull-right">
        <a class="btn btn-sm btn-default add-item" href="/user"><i class="glyphicon glyphicon-arrow-left"></i><?php echo $this->translate('Back')?></a>
        <a class="btn btn-sm btn-default add-item" onchange="formReset()"><i class="glyphicon glyphicon-repeat"></i><?php echo $this->translate('Reset')?></a>
        <a class="btn btn-sm btn-default add-item" onclick="formSave()"><i class="glyphicon glyphicon-saved"></i><?php echo $this->translate('Save')?></a>
        <a class="btn btn-sm btn-default add-item" onclick="formSaveAndContinue();"><i class="glyphicon glyphicon-save"></i><?php echo $this->translate('Save and Continue Edit')?></a>
    </div>
    <div class="clearfix"></div>
</div>