<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/17/13
 */
?>
<?php $form = $this->form;?>
<?php $form->setAttribute('action', $this->currentUrl());?>
<?php $form->prepare();?>
<div class="page-header">
    <div class="pull-left">
        <h2><?php echo $this->translate('Add User')?></h2>
    </div>
    <div class="pull-right">
        <a class="btn btn-sm btn-default add-item" href="/user"><i class="glyphicon glyphicon-arrow-left"></i><?php echo $this->translate('Back')?></a>
        <a class="btn btn-sm btn-default add-item" onclick="formReset('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-repeat"></i><?php echo $this->translate('Reset')?></a>
        <a class="btn btn-sm btn-default add-item" onclick="formSave('<?php echo $form->getAttribute('name');?>')"><i class="glyphicon glyphicon-saved"></i><?php echo $this->translate('Save')?></a>
        <a class="btn btn-sm btn-default add-item" onclick="formSaveAndContinue('<?php echo $form->getAttribute('name');?>');"><i class="glyphicon glyphicon-save"></i><?php echo $this->translate('Save and Continue Edit')?></a>
    </div>
    <div class="clearfix"></div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="container">
            <?php echo $this->form()->openTag($form);?>
            <?php echo $this->formRow($form->get('id'));?>
            <?php echo $this->formRow($form->get('csrf'));?>
            <?php echo $this->formRow($form->get('continue'));?>
            <?php echo $this->partial('partial/form-messages.phtml',array('msg' => $this->msg))?>
            <div class="row form-row">
                <div class="col-md-4">
                    <div class="control-label"><?php echo $this->translate('Role')?> </div>
                </div>
                <div class="col-md-4">
                    <?php echo $this->formRow($form->get('role'));?>
                </div>
            </div>
            <div class="row form-row">
                <div class="col-md-4">
                    <div class="control-label"><?php echo $this->translate('First name')?> </div>
                </div>
                <div class="col-md-4">
                    <?php echo $this->formRow($form->get('first_name'));?>
                </div>
            </div>
            <div class="row form-row">
                <div class="col-md-4">
                    <div class="control-label"><?php echo $this->translate('Last name')?> </div>
                </div>
                <div class="col-md-4">
                    <?php echo $this->formRow($form->get('last_name'));?>
                </div>
            </div>
            <div class="row form-row">
                <div class="col-md-4">
                    <div class="control-label"><?php echo $this->translate('Email')?> </div>
                </div>
                <div class="col-md-4">
                    <?php echo $this->formRow($form->get('email'));?>
                </div>
            </div>
            <div class="row form-row">
                <div class="col-md-4">
                    <div class="control-label"><?php echo $this->translate('Password')?> </div>
                </div>
                <div class="col-md-4">
                    <?php echo $this->formRow($form->get('password'));?>
                </div>
            </div>
            <div class="row form-row">
                <div class="col-md-4">
                    <div class="control-label"><?php echo $this->translate('Status')?> </div>
                </div>
                <div class="col-md-4">
                    <?php echo $this->formRow($form->get('status'));?>
                </div>
            </div>
            <div class="row form-row">
                <div class="col-md-4">
                    <div class="control-label"><?php echo $this->translate('Note')?> </div>
                </div>
                <div class="col-md-4">
                    <?php echo $this->formRow($form->get('note'));?>
                </div>
            </div>
            <?php echo $this->form()->closeTag();?>
        </div>

    </div>
</div>