<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/17/13
 */
?>
<div class="page-header">
    <div class="pull-left">
        <h2>Manage Users</h2>
    </div>
    <div class="pull-right">
        <a class="btn btn-success btn-sm pull-right add-item" href="/user/add">
            <i class="glyphicon glyphicon-plus"></i>
            Add new user
        </a>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <table class="display table table-striped table-condensed table-bordered" id="example" cellpadding="0" cellspacing="0">
        <thead>
        <tr>
            <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
            <th><?php echo $this->translate('ID')?></th>
            <th><?php echo $this->translate('First name')?></th>
            <th><?php echo $this->translate('Last name')?></th>
            <th><?php echo $this->translate('Username')?></th>
            <th><?php echo $this->translate('Email')?></th>
            <th><?php echo $this->translate('Created at')?></th>
            <th><?php echo $this->translate('Status')?></th>
            <th class="action"><?php echo $this->translate('Action')?></th>
        </tr>
        </thead>
        <tbody>
        <?php if(!empty($this->users)):?>
        <?php foreach($this->users as $row):?>
        <tr>
            <td class="col-checkbox"><input type="checkbox" class="check-item" value="<?php echo $row->id?>"></td>
            <td><?php echo $row->id?></td>
            <td><?php echo $row->first_name?></td>
            <td><?php echo $row->last_name?></td>
            <td><?php echo $row->username?></td>
            <td><?php echo $row->email?></td>
            <td><?php echo date('Y-m-d H:i:s',$row->created_at)?></td>
            <td><?php echo ((int)$row->status == 1) ? 'Activated' : 'Disabled';?></td>
            <td class="action">
                <a class="btn btn-xs btn-primary btn-edit" href="/user/detail/id/<?php echo $row->id?>">
                    <i class="glyphicon glyphicon-edit"></i>
                    <?php echo $this->translate('Edit') ?>
                </a>
                <a class="btn btn-xs btn-danger btn-delete" href="/user/delete/id/<?php echo $row->id?>">
                    <i class="glyphicon glyphicon-trash"></i>
                    <?php echo $this->translate('Delete') ?>
                </a>
            </td>
        </tr>
        <?php endforeach;?>
        <?php endif;?>
        </tbody>
    </table>
</div>