<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/17/13
 */
?>
<div class="page-header">
    <div class="pull-left">
        <h2><?php echo $this->translate('Manage Resources') ?></h2>
    </div>
    <div class="pull-right">
        <a onclick="formConfirm('resource');" class="btn btn-danger btn-sm add-item">
            <i class="glyphicon glyphicon-trash"></i>
            <?php echo $this->translate('Delete selected') ?>
        </a>
        <a class="btn btn-success btn-sm add-item" href="/resource/add">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->translate('Add new resource') ?>
        </a>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <form id="resource" action="/resource/delete" method="post" enctype="multipart/form-data">
        <table class="display table table-striped table-condensed table-bordered example" id="example" cellpadding="0" cellspacing="0">
            <thead>
            <tr>
                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                <th><?php echo $this->translate('ID')?></th>
                <th><?php echo $this->translate('Name')?></th>
                <th><?php echo $this->translate('Path')?></th>
                <th class="action"><?php echo $this->translate('Action')?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($this->rowset)):?>
                <?php foreach($this->rowset as $row):?>
                    <tr>
                        <td class="col-checkbox"><input name="id[]" type="checkbox" class="check-item" value="<?php echo $row->resource_id?>"></td>
                        <td><?php echo $row->resource_id?></td>
                        <td><?php echo $row->name?></td>
                        <td><?php echo $row->path?></td>
                        <td class="action">
                            <a class="btn btn-xs btn-primary btn-edit" href="/resource/detail/id/<?php echo $row->resource_id?>">
                                <i class="glyphicon glyphicon-edit"></i>
                                <?php echo $this->translate('Edit') ?>
                            </a>
                            <a class="btn btn-xs btn-danger btn-delete" href="/resource/delete/id/<?php echo $row->resource_id?>">
                                <i class="glyphicon glyphicon-trash"></i>
                                <?php echo $this->translate('Delete') ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
        </table>
    </form>
</div>