<?php
/**
 * Created by Nguyen Tien Dat.
 * Email : datnguyen.cntt@gmail.com
 * Date: 10/23/13
 */
 ?>
<div class="page-header">
    <div class="pull-left">
        <h2><?php echo $this->translate('Manage Languages') ?></h2>
    </div>
    <div class="pull-right">
        <a onclick="formConfirm('languages');" class="btn btn-danger btn-sm add-item">
            <i class="glyphicon glyphicon-trash"></i>
            <?php echo $this->translate('Delete selected') ?>
        </a>
        <a class="btn btn-success btn-sm add-item" href="<?php echo $this->getUrl('language/add')?>">
            <i class="glyphicon glyphicon-plus"></i>
            <?php echo $this->translate('Add new') ?>
        </a>
    </div>
    <div class="clearfix"></div>
</div>
<div class="row">
    <form id="user" action="<?php echo $this->getUrl('language/delete')?>" method="post" enctype="multipart/form-data">
        <table class="display table table-striped table-condensed table-bordered" id="example" cellpadding="0" cellspacing="0">
            <thead>
            <tr>
                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                <th><?php echo $this->translate('ID')?></th>
                <th><?php echo $this->translate('Country')?></th>
                <th><?php echo $this->translate('Code')?></th>
                <th><?php echo $this->translate('Sort Order')?></th>
                <th><?php echo $this->translate('File Path')?></th>
                <th class="action4"><?php echo $this->translate('Action')?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($this->rowset)):?>
                <?php foreach($this->rowset as $row):?>
                    <tr>
                        <td class="col-checkbox"><input name="ids[]" type="checkbox" class="check-item" value="<?php echo $row->id?>"></td>
                        <td><?php echo $row->id?></td>
                        <td><?php echo $row->lang_country?></td>
                        <td><?php echo $row->lang_code?></td>
                        <td><?php echo $row->sort_order?></td>
                        <td><?php echo $row->file_path?></td>
                        <td class="action4">
                            <a class="btn btn-xs btn-primary btn-edit" href="/language/edit/id/<?php echo $row->id?>">
                                <i class="glyphicon glyphicon-edit"></i>
                                <?php echo $this->translate('Edit') ?>
                            </a>
                            <a onclick="confirmDelete('/language/delete/id/<?php echo $row->id?>')" class="btn btn-xs btn-danger btn-delete" >
                                <i class="glyphicon glyphicon-trash"></i>
                                <?php echo $this->translate('Delete') ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
        </table>
    </form>
</div>