<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <!--<meta charset="utf-8">-->
        <?php header('Content-Type: text/html; charset=utf-8');?>
        <?php echo $this->headTitle()->setSeparator(' :: ')->setAutoEscape(false)->prepend($this->__('PMAS')) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=product-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->getUrl('css/style.css'))
                        ->prependStylesheet($this->getUrl('css/chosen.min.css'))
                        ->prependStylesheet($this->getUrl('css/colorbox.css'))
                        ->prependStylesheet($this->getUrl('css/jqplot/jquery.jqplot.min.css'))
                        ->prependStylesheet($this->getUrl('css/jquery.ui.autocomplete.min.css'))
                        ->prependStylesheet($this->getUrl('css/jquery-ui-1.10.3.custom.css'))
                        ->prependStylesheet($this->getUrl('css/demo_table.css'))
                        ->prependStylesheet($this->getUrl('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->getUrl('css/bootstrap.min.css')) ?>
        <!-- Scripts -->
        <script type="text/javascript">
            var siteurl = '<?php echo $this->getUrl();?>';
            var currentroute = '<?php echo $this->getUrl($this->url())?>';
            var currenturl = '<?php echo $this->core()->getCurrentUrl()?>';
            var currentpath = '<?php echo $this->core()->getCurrentPath()?>';
        </script>
        <?php echo $this->headScript()
            ->prependFile($this->getUrl('js/pmas.js'))
            ->prependFile($this->getUrl('js/chosen.jquery.min.js'))
            ->prependFile($this->getUrl('/js/jquery.colorbox-min.js'))
            ->prependFile($this->getUrl('/js/jqplot/plugins/jqplot.cursor.min.js'))
            ->prependFile($this->getUrl('/js/jqplot/plugins/jqplot.dateAxisRenderer.min.js'))
            ->prependFile($this->getUrl('/js/jqplot/plugins/jqplot.highlighter.js'))
            ->prependFile($this->getUrl('/js/jqplot/jquery.jqplot.min.js'))
            ->prependFile($this->getUrl('/js/bootbox.js'))
            ->prependFile($this->getUrl('/js/jquery.ui.autocomplete.min.js'))
            ->prependFile($this->getUrl('/js/jquery.ui.datepicker.js'))
            ->prependFile($this->getUrl('/js/jquery-ui.custom.min.js'))
            ->prependFile($this->getUrl('/js/jquery.dataTables.min.js'))
            ->prependFile($this->getUrl('/js/bootstrap.min.js'))
            ->prependFile($this->getUrl('/js/jquery.min.js'))
            ->prependFile($this->getUrl('/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->getUrl('/js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <h1><a href="/"><?php echo $this->__('PMAS Admin');?></a></h1>
                </div>
                <div class="col-md-4" style="height: 60px;">
                    <img src="<?php echo $this->basePath('images/banner468x60.jpg')?>" width="468" height="60">
                </div>
                <div class="col-md-6">
                    <ul class="pull-right header-items">
                        <li>
                            <?php echo $this->lang()->getLanguagesDropdown()?>
                        </li>
                        <li><?php echo $this->__('Logged in as')?> <a class="btn-link"><?php echo $this->username()?></a> |</li>
                        <li><?php echo date('l, F j, Y',time())?> |</li>
                        <li><a href="<?php echo $this->getUrl('logout')?>" class="btn-link"><?php echo $this->__('Logout');?></a></li>
                    </ul>
                </div>
            </div>
        </div>

    </header>
    <?php
    $role = $this->role();
    $navigation = 'top_menu_navigation';
    if($role == 'super_admin'){
        $navigation = 'super_admin_navigation';
    }
    echo $this->navigation($navigation)
        ->menu()
        ->setMinDepth(0)
        ->setPartial('admin/topmenu');
    ?>
    <div class="container">
        <?php echo $this->partial('partial/messages.phtml')?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <div class="col-md-12">
                    <p>&copy; 2005 - <?php echo date('Y') ?> <?php echo $this->__('by')?> PMAS <?php echo $this->__('All rights reserved.') ?></p>
                </div>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    <script type="text/javascript">
        var config = {
            '.chosen-select'           : {},
            '.chosen-select-deselect'  : {allow_single_deselect:true},
            '.chosen-select-no-single' : {disable_search_threshold:10},
            '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
            '.chosen-select-width'     : {width:"95%"}
        }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
    </script>
    </body>
</html>
