<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/28/13
 */
?>
<div class="pull-right" style="margin-bottom: 15px;">
    <a class="btn">
        <?php echo $this->translate('Export to')?>
    </a>
    <div class="btn-group">
        <select class="form-control" id="historical-export-format" name="historical_export_format">
            <option value="none"><?php echo $this->translate('Select format')?></option>
            <option value="csv"><?php echo $this->translate('CSV')?></option>
            <option value="xls"><?php echo $this->translate('Excel 2003')?></option>
            <option value="xlsx"><?php echo $this->translate('Excel 2007')?></option>
        </select>
    </div>
    <a class="btn btn-warning btn-sm" onclick="exportHistorical('<?php echo $this->id ?>')">
        <i class="glyphicon glyphicon-export"></i>
        <?php echo $this->translate('Export')?>
    </a>
</div>
<?php if($this->search == 'highest'):?>
    <div class="tab-content">
        <div class="tab-pane active" id="table-view">
            <table class="display table table-striped table-condensed table-bordered example2" id="example2" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th class="col-checkbox"><input type="checkbox" class="checkall" name="checkall"></th>
                    <th><?php echo $this->translate('Date')?></th>
                    <th><?php echo $this->translate('Price')?></th>
                    <th><?php echo $this->translate('Price in HKD')?></th>
                </tr>
                </thead>
                <tbody>
                <?php if(!empty($this->highest)):?>
                    <?php $highest = $this->highest;?>
                    <tr>
                        <td class="col-checkbox"><input class="checkitem" name="product" type="checkbox" value="<?php echo $highest['product_id']?>"></td>
                        <td><?php echo ($highest['time'] != null) ? date('d-m-Y',(int)$highest['time']) : 'N/A'?></td>
                        <td><?php echo $this->price()->format($highest['price'])?></td>
                        <td><?php echo $this->price()->format($highest['exchange_price'])?></td>
                    </tr>
                <?php endif;?>

                </tbody>
            </table>
        </div>
        <div class="tab-pane" id="chart-view">
            <div id="chart-demo" class="chart-demo">
                <h2><?php echo $this->translate('No chart');?></h2>
            </div>
        </div>
    </div>
<?php elseif($this->search == ''):?>
<?php endif;?>

<script type="text/javascript">
    $(function(){
        $(".checkall").on("click", function () {
            var checkedd = $(this).is(":checked");
            $(".checkitem").prop('checked',checkedd);
        });
        $('.example2').dataTable( {
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [ 0 ] }
            ],
            "aaSorting": [[1, 'asc']],
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "sPaginationType": "full_numbers"
        } );
    });

</script>