<?php $container = $this->navigation('navigation')->breadcrumbs()  ?>
<?php /* @var $container \Zend\View\Helper\Navigation\Breadcrumbs */ ?>
<?php $navigation = $container->getContainer() ?>
<?php /* @var $navigation \Zend\Navigation\Navigation */ ?>
<ul class="breadcrumb">
    <li><a href="/admin"><?php echo $this->translate('Dashboard')?></a> <i class="icon-angle-right"></i></li>
    <?php $active = $container->findActive($navigation) ?>
    <?php if(count($this->pages)):?>
        <?php foreach($this->pages as $page): ?>
            <?php /* @var $page \Zend\Navigation\Page\Mvc */ ?>
            <?php if( ! $page->isActive()): ?>
                <li>
                    <a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ?></a>
                    <i class="icon-angle-right"></i>
                </li>
            <?php else: ?>
                <li class="active">
                    <?php if($container->getLinkLast()): ?><a href="<?php echo $page->getHref() ?>"><?php endif ?>
                        <span><?php echo $page->getLabel() ?></span>
                        <?php if($container->getLinkLast()): ?><a href="<?php echo $page->getHref() ?>"><?php endif ?>
                </li>
            <?php endif ?>
        <?php endforeach ?>
    <?php endif;?>
</ul>
