<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/12/13
 */
?>
<?php
$role = $this->menu()->getRole();
$groups = $this->menu()->getResourceGroups();
?>
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <?php if($role == 'super_admin'):?>
                <ul class="nav navbar-nav nav-top">
                    <li class="">
                        <a href="/index/" class="nav-header">
                            <?php echo $this->__('Dashboard')?> </a>
                    </li>
                    <li class="">
                        <a href="/recycler/" class="nav-header">
                            <?php echo $this->__('Recycler')?>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="/product/" data-toggle="dropdown" class="dropdown-toggle">
                            <?php echo $this->__('TDM Model')?>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <?php $countries = $this->core()->getAvailableCountries();?>
                            <?php foreach($countries as $country):?>
                                <li><a href="<?php echo $this->getUrl('product').'?tdmcountry='.$country->country_id.'&rcountry='.$country->country_id?>"><?php echo $country->name?></a></li>
                            <?php endforeach;?>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <span><?php echo $this->__('Exchange Rate')?></span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/exchange/">
                                    <?php echo $this->__('Historical Exchange Rate')?> </a>
                            </li>
                            <li>
                                <a href="/exchange/update/">
                                    <?php echo $this->__('Update Exchange Rate')?> </a>
                            </li>
                        </ul>
                    </li>

                    <li class="dropdown ">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <span><?php echo $this->__('System')?></span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->getUrl('language')?>">
                                    <?php echo $this->__('Manage Languages')?> </a>
                            </li>
                            <li>
                                <a href="/soap/user/">
                                    <?php echo $this->__('Manage Soap Users')?> </a>
                            </li>
                            <li>
                                <a href="/user/">
                                    <?php echo $this->__('Manage Users')?> </a>
                            </li>
                            <li>
                                <a href="/role/">
                                    <?php echo $this->__('Manage Roles')?> </a>
                            </li>
                            <li>
                                <a href="/resource/">
                                    <?php echo $this->__('Manage Resources')?> </a>
                            </li>
                            <li>
                                <a href="/exchange/country/">
                                    <?php echo $this->__('Manage Countries')?> </a>
                            </li>
                            <li>
                                <a href="/condition/tdm/">
                                    <?php echo $this->__('Condition Management')?> </a>
                            </li>
                            <li>
                                <a href="/product/type/">
                                    <?php echo $this->__('Product Type Management')?> </a>
                            </li>
                            <li>
                                <a href="/product/brand/">
                                    <?php echo $this->__('Brand Management')?> </a>
                            </li>
                            <li>
                                <a href="/product/popular/">
                                    <?php echo $this->__('Popular Product')?> </a>
                            </li>
                        </ul>
                    </li>

                    <li class="">
                        <a href="/help/" class="nav-header">
                            <?php echo $this->__('Help')?> </a>
                    </li>
                </ul>
            <?php else:?>
                <ul class="nav navbar-nav nav-top">
                    <li class="">
                        <a href="/index/" class="nav-header">
                            <?php echo $this->__('Dashboard')?> </a>
                    </li>
                    <?php if(!empty($groups)):?>
                    <?php if(in_array('recycler',$groups)):?>
                        <li class="">
                            <a href="/recycler/" class="nav-header">
                                <?php echo $this->__('Recycler')?> </a>
                        </li>
                    <?php endif;?>
                    <?php if(in_array('tdm-product',$groups)):?>
                        <li class="">
                            <a href="/product/" class="nav-header">
                                <?php echo $this->__('TDM Model')?> </a>
                        </li>
                    <?php endif;?>
                    <?php if(in_array('exchange',$groups)):?>
                        <li class="dropdown ">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                <span><?php echo $this->__('Exchange Rate')?></span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/exchange/">
                                        <?php echo $this->__('Historical Exchange Date')?> </a>
                                </li>
                                <li>
                                    <a href="/exchange/update/">
                                        <?php echo $this->__('Update Exchange Rate')?> </a>
                                </li>
                            </ul>
                        </li>
                    <?php endif;?>
                    <?php if(in_array('user',$groups) || in_array('role',$groups) || in_array('resource',$groups)
                            || in_array('country',$groups) || in_array('tdm-condition',$groups)
                            || in_array('product-type',$groups) || in_array('brand',$groups) || in_array('tdm-product',$groups)
                            || in_array('soap',$groups) || in_array('language',$groups)):?>
                        <li class="dropdown ">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                <span><?php echo $this->__('System')?></span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <?php if(in_array('soap',$groups)):?>
                                    <li>
                                        <a href="<?php echo $this->getUrl('language')?>">
                                            <?php echo $this->__('Manage Languages')?> </a>
                                    </li>
                                <?php endif;?>

                                <?php if(in_array('soap',$groups)):?>
                                    <li>
                                        <a href="/soap/user/">
                                            <?php echo $this->__('Manage Soap Users')?> </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('user',$groups)):?>
                                    <li>
                                        <a href="/user/">
                                            <?php echo $this->__('Manage Users')?> </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('role',$groups)):?>
                                    <li>
                                        <a href="/role/">
                                            <?php echo $this->__('Manage Roles')?> </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('resource',$groups)):?>
                                    <li>
                                        <a href="/resource/">
                                            <?php echo $this->__('Manage Resources')?> </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('country',$groups)):?>
                                    <li>
                                        <a href="/exchange/country/">
                                            <?php echo $this->__('Manage Countries')?> </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('tdm-condition',$groups)):?>
                                    <li>
                                        <a href="/condition/tdm/">
                                            <?php echo $this->__('TDM Condition Management')?> </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('product-type',$groups)):?>
                                    <li>
                                        <a href="/product/type/">
                                            <?php echo $this->__('Product Type Management')?> </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('brand',$groups)):?>
                                    <li>
                                        <a href="/product/brand/">
                                            <?php echo $this->__('Brand Management')?> </a>
                                    </li>
                                <?php endif;?>
                                <?php if(in_array('tdm-product',$groups)):?>
                                    <li>
                                        <a href="/product/popular/">
                                            <?php echo $this->__('Popular Product')?> </a>
                                    </li>
                                <?php endif;?>
                            </ul>
                        </li>
                    <?php endif;?>
                    <?php endif;?>

                    <li class="">
                        <a href="/help/" class="nav-header">
                            <?php echo $this->__('Help')?> </a>
                    </li>
                </ul>
            <?php endif;?>

        </div><!-- /.navbar-collapse -->
    </div>
</nav>