<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 10/17/13
 */
?>
<?php $filter = $this->filter;?>
<select class="chosen-select form-control is_searchable" name="higher" id="price_percentage" data-placeholder="<?php echo $this->__('Choose a percentage')?>">
    <option value=""></option>
    <option value="reset"><?php echo $this->__('Reset filter')?></option>
    <?php $values = array(5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95)?>
    <?php foreach($values as $value):?>
        <option <?php if($filter && ($filter) == $value){echo 'selected';}?> value="<?php echo $value?>"><?php echo $this->__('Price higher than')?> <?php echo $value?>%</option>
    <?php endforeach;?>
</select>