<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 10/17/13
 */
?>
<select class="chosen-select form-control" id="price_percentage" data-placeholder="<?php echo $this->__('Choose a percentage')?>">
    <option value=""></option>
    <option value="5"><?php echo $this->__('Price higher than')?> 5%</option>
    <option value="10"><?php echo $this->__('Price higher than')?> 10%</option>
    <option value="15"><?php echo $this->__('Price higher than')?> 15%</option>
    <option value="20"><?php echo $this->__('Price higher than')?> 20%</option>
    <option value="25"><?php echo $this->__('Price higher than')?> 25%</option>
    <option value="30"><?php echo $this->__('Price higher than')?> 30%</option>
    <option value="35"><?php echo $this->__('Price higher than')?> 35%</option>
    <option value="40"><?php echo $this->__('Price higher than')?> 40%</option>
    <option value="45"><?php echo $this->__('Price higher than')?> 45%</option>
    <option value="50"><?php echo $this->__('Price higher than')?> 50%</option>
    <option value="55"><?php echo $this->__('Price higher than')?> 55%</option>
    <option value="60"><?php echo $this->__('Price higher than')?> 60%</option>
    <option value="65"><?php echo $this->__('Price higher than')?> 65%</option>
    <option value="70"><?php echo $this->__('Price higher than')?> 70%</option>
    <option value="75"><?php echo $this->__('Price higher than')?> 75%</option>
    <option value="80"><?php echo $this->__('Price higher than')?> 80%</option>
    <option value="85"><?php echo $this->__('Price higher than')?> 85%</option>
    <option value="90"><?php echo $this->__('Price higher than')?> 90%</option>
    <option value="95"><?php echo $this->__('Price higher than')?> 95%</option>
</select>