<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/22/13
 */
?>
<?php echo $this->partial('partial/form-messages.phtml',array('msg' => $this->msg))?>
<div class="page-header">
    <div class="pull-left">
        <h3><?php echo $this->translate('Manage Countries')?></h3>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
<div class="row">
    <form id="countries" action="/exchange/delete-country" method="post" enctype="multipart/form-data">
        <div class="pull-right">
            <a class="btn btn-danger btn-sm" style="margin-bottom: 15px;">
                <i class="glyphicon glyphicon-trash"></i>
                <?php echo $this->translate('Delete Selected Countries')?>
            </a>
        </div>
        <div class="row clearfix">&nbsp;</div>
        <table class="display table table-striped table-condensed table-bordered example" id="country" cellpadding="0" cellspacing="0">
            <thead>
            <tr>
                <th class="col-checkbox"><input class="check-all" value="" type="checkbox"></th>
                <th><?php echo $this->translate('ID')?></th>
                <th><?php echo $this->translate('Name')?></th>
                <th class="action"><?php echo $this->translate('Action')?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($this->countries)):?>
                <?php foreach($this->countries as $row):?>
                    <tr>
                        <td class="col-checkbox"><input name="ids[]" type="checkbox" class="check-item" value="<?php echo $row->country_id?>"></td>
                        <td><?php echo $row->country_id?></td>
                        <td><?php echo $row->name?></td>
                        <td class="action">
                            <a class="btn btn-xs btn-warning btn-edit" href="/exchange/country/id/<?php echo $row->country_id?>">
                                <i class="glyphicon glyphicon-edit"></i>
                                <?php echo $this->translate('Edit')?>
                            </a>
                            <a onclick="confirmDelete('/exchange/delete-country/id/<?php echo $row->country_id?>')" class="btn btn-xs btn-danger btn-delete">
                                <i class="glyphicon glyphicon-trash"></i>
                                <?php echo $this->translate('Delete')?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
        </table>
    </form>
</div>
<?php $form = $this->form;?>
<?php $form->setAttribute('action', $this->currentUrl());?>
<?php $form->prepare();?>
<div class="row" style="margin-top: 30px;">
    <div class="container" style="width: 50%;">
        <?php echo $this->form()->openTag($form);?>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Add Country</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="row row-form">
                            <div class="col-md-3">
                                <div class="control-label"><span>Country Name</span></div>
                            </div>
                            <div class="col-md-9">
                                <?php echo $this->formRow($form->get('country_name'));?>
                                <?php echo $this->formRow($form->get('country_id'));?>
                                <?php echo $this->formRow($form->get('csrf'));?>
                            </div>

                        </div>
                        <div class="row form-row">
                            <div class="col-md-3"></div>
                            <div class="col-md-9">
                                <button class="btn btn-sm btn-success">
                                    <i class="glyphicon glyphicon-send"></i>
                                    Submit
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>