<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/25/13
 */
?>
<?php
$data = array();
if(!empty($this->rowset)){
    foreach($this->rowset as $row){
        $data[] = array(
            'exchange' => $row->exchange_rate,
            'date' => date('Y-m-d',$row->time)
        );
    }
}else{
    echo '<h3>No data availables.</h3>';
}
?>
<div id="chart1" style="min-height: 600px; width:90%;"></div>
<script type="text/javascript">
    $(function(){
        /**
         * Exchange Rate chart
         */
        var line1 = new Array();
        <?php if(!empty($data)):?>
        <?php foreach($data as $index=>$row):?>
        var item<?php echo $index?> = new Array();
        item<?php echo $index?>.push('<?php echo $row['date']?>');
        item<?php echo $index?>.push(<?php echo $row['exchange']?>);
        line1.push(item<?php echo $index?>);
        <?php endforeach;?>
        <?php endif;?>
        var plot1 = $.jqplot('chart1', [line1], {
            title:'Exchange Rate Chart',
            axes:{
                xaxis:{
                    renderer:$.jqplot.DateAxisRenderer
                },
                yaxis:{
                    tickOptions:{
                        formatString:'%.2f'
                    }
                }
            },
            highlighter: {
                show: true,
                sizeAdjust: 7.5
            },
            cursor: {
                show: false
            }
        });
    });
</script>