<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/25/13
 */
?>
<div class="pull-right" style="margin-bottom: 15px;">
    <a class="btn">
        <?php echo $this->__('Export to')?>
    </a>
    <div class="btn-group">
        <select class="form-control" id="export-format" name="export_format">
            <option value="none"><?php echo $this->__('Select format')?></option>
            <option value="csv"><?php echo $this->__('CSV')?></option>
            <option value="xls"><?php echo $this->__('Excel 2003')?></option>
            <option value="xlsx"><?php echo $this->__('Excel 2007')?></option>
        </select>
    </div>
    <a class="btn btn-warning btn-sm" onclick="exportExchange('<?php echo $this->currency?>','<?php echo $this->start?>','<?php echo $this->end?>')">
        <i class="glyphicon glyphicon-export"></i>
        <?php echo $this->__('Export')?>
    </a>
</div>
<div class="clearfix">&nbsp;</div>
<table class="display table table-striped table-condensed table-bordered" id="list-exchange" cellpadding="0" cellspacing="0">
    <thead>
    <tr>
        <th><?php echo $this->__('Date')?></th>
        <th><?php echo $this->__('Country')?></th>
        <th><?php echo $this->__('Exchange Rate')?></th>
    </tr>
    </thead>
    <tbody>
    <?php if(!empty($this->rowset)):?>
    <?php foreach($this->rowset as $row):?>
        <tr>
            <td><?php echo date('d-m-Y',$row->time)?></td>
            <td><?php echo $this->country($row->country_id) ?></td>
            <td><?php echo $row->exchange_rate?></td>
        </tr>
    <?php endforeach;?>
    <?php endif;?>

    </tbody>
</table>