<?php
/**
 * Created by Nguyen Tien Dat.
 * Date: 9/14/13
 */
?>
<div class="page-header">
    <div class="pull-left">
        <h3>New Exchange Rate</h3>
    </div>
    <div class="pull-right">
        <a class="btn btn-sm btn-default add-item"><i class="glyphicon glyphicon-arrow-left"></i>Back</a>
        <a class="btn btn-sm btn-default add-item"><i class="glyphicon glyphicon-repeat"></i>Reset</a>
        <a class="btn btn-sm btn-default add-item"><i class="glyphicon glyphicon-saved"></i>Save model</a>
        <a class="btn btn-sm btn-default add-item"><i class="glyphicon glyphicon-save"></i>Save model and Edit</a>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>
<div class="panel">
    <div class="panel-body">
        <div class="row form-row">
            <div class="col-md-3"><span class="pull-right">Currency*</span></div>
            <div class="col-md-9">
                <select class="form-control" style="width: 90px">
                    <option>USD</option>
                    <option>HKD</option>
                </select>
            </div>
        </div>
        <div class="row form-row">
            <div class="col-md-3"><span class="pull-right">Date*</span></div>
            <div class="col-md-9">
                <div class="input-group" style="width: 150px;float: left;">
                    <input type="text" class="form-control datepicker">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                </div>
            </div>
        </div>
        <div class="row form-row">
            <div class="col-md-3"><span class="pull-right">Exchange Rate*</span></div>
            <div class="col-md-9"><input type="text" class="form-control" style="width: 150px;"></div>
        </div>
    </div>
</div>